/* Integrate the V5 screens with the new, confirmed-money reports. */
const oldDashboard=renderDashboard;
renderDashboard=function(){oldDashboard();let success=S.opportunities.filter(o=>o.status==='success'&&o.confirmedAt&&o.receiverType==='member');q('#kpiOppValue').textContent=money(sum(success,'confirmedValue'));q('#kpiOppValue').parentElement.querySelector('span')&&(q('#kpiOppValue').parentElement.querySelector('span').textContent='Doanh thu đã xác nhận');};
renderReports=function(){q('#reportSummary').innerHTML=stats([['Hội viên',actives().length],['Buổi họp',S.meetings.length],['Cơ hội đã trao',S.opportunities.length],['Doanh thu xác nhận',money(sum(S.opportunities.filter(o=>o.status==='success'&&o.confirmedAt&&o.receiverType==='member'),'confirmedValue'))]])+'<a class="btn btn-wine" href="reports.html">Mở báo cáo chi tiết theo kỳ</a>'};
renderOpportunityDashboard=function(){let ops=S.opportunities,confirmed=ops.filter(o=>o.confirmedAt&&o.status==='success');q('#oppTotalCount').textContent=ops.length;q('#oppTotalValue').textContent=money(sum(ops,'value'));q('#opportunitiesTable').innerHTML=ops.slice().reverse().map(o=>`<tr><td>${fmtDT(o.createdAt)}</td><td>${esc(memberName(o.giverId))}<br><small>${esc(S.members.find(m=>m.id===o.giverId)?.phone)}</small></td><td>${esc(o.receiverName)}</td><td>${esc(o.type)}</td><td>${money(o.value)}</td><td>${o.confirmedAt?statusChip(o.status):'<span class="chip gold">Chưa xác nhận</span>'}</td></tr>`).join('');q('#oppAdvanced')?.remove();q('#section-opportunities').insertAdjacentHTML('beforeend',`<div id="oppAdvanced">${stats([['Giá trị dự kiến',money(sum(ops,'value'))],['Cơ hội đã thành công',confirmed.length],['Doanh thu hội viên xác nhận',money(sum(confirmed.filter(o=>o.receiverType==='member'),'confirmedValue'))]])}<a class="btn btn-outline" href="reports.html">Bộ lọc thời gian & báo cáo chi tiết</a></div>`)};
renderFees=function(){q('#feesTable').innerHTML=S.obligations.map(o=>`<tr><td>${esc(memberName(o.memberId))}</td><td>${esc(o.label)}</td><td>${fmtDate(o.due)}</td><td>${money(debtFor(o))}</td></tr>`).join('')||'<tr><td colspan="4">Lập nghĩa vụ phí tại Sổ quỹ & Công nợ.</td></tr>';let p=q('#section-fees');if(p&&!q('#newFeeLink'))p.insertAdjacentHTML('afterbegin','<a id="newFeeLink" class="btn btn-wine" href="finance.html">Phí kết nạp, tái phí, tri ân & gạch nợ</a>')};
window.confirmFee=()=>location.href='finance.html';
// Existing V5 mutators are guarded as well as their visible entry points.
for(const name of ['addMember','editMember','viewMember','addExternalPerson','saveExternalPerson','addMeeting','saveMeeting','applyMemberStatus','resetMemberPassword','toggleMemberAccount']){
 const old=window[name];if(old)window[name]=function(...args){if(!canLead())return toast('Chỉ Admin / Chủ tịch được thao tác');return old(...args)};
}
const originalCompletePassword=window.completePasswordChange;window.completePasswordChange=id=>{if(currentUser()?.id!==id)return;originalCompletePassword(id)};
const oldGuestStatus=window.updateGuestStatus;window.updateGuestStatus=(id,status)=>{if(!canDept('guests'))return;oldGuestStatus(id,status)};
const oldApproveIntegrated=window.approveRequest;window.approveRequest=id=>{if(!canLead())return;let a=S.approvals.find(a=>a.id===id);if(a?.type==='profile'){
 const target=S.members.find(m=>m.id===a.entityId);if(!target||S.members.some(m=>m.id!==target.id&&m.phone===a.payload.phone))return toast('Số điện thoại xung đột với hồ sơ khác');
 }if(a?.type==='finance_edit'){let f=S.finance.find(f=>f.id===a.entityId);if(!f||financeLocked(f.date))return toast('Phiếu thuộc kỳ đã khóa sổ')}
 oldApproveIntegrated(id);if(a?.type==='profile'&&a.status==='approved'){let m=S.members.find(m=>m.id===a.entityId),u=S.users.find(u=>u.memberId===m.id);if(u){u.phone=m.phone;u.username=m.phone;u.email=m.email;save()}}
};
// Persistent blobs must succeed; never pretend a filename alone is an uploaded file.
persistInputFiles=async function(input,max=10,group='other'){let fs=[...(input?.files||[])];if(fs.length>max)throw Error('Tối đa '+max+' tệp cho mục này');if(fs.some(f=>f.size>20*1024*1024))throw Error('Mỗi tệp tối đa 20 MB');if(!fs.length)return [];const db=await openFileDB(),out=[];try{for(const f of fs){const key=uid('FILE');await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({key,blob:f,name:f.name,type:f.type,size:f.size,group,createdAt:iso()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});out.push({storageKey:key,name:f.name,size:f.size,type:f.type,typeGroup:group,lastModified:f.lastModified})}return out}finally{db.close()}};
// File visibility follows the owning business record inside this local prototype.
const oldDownload=window.downloadStoredFile;window.downloadStoredFile=key=>{const owner=S.members.find(m=>m.documents?.some(d=>d.storageKey===key)),fin=S.finance.find(f=>f.files?.some(d=>d.storageKey===key)),training=S.training.find(t=>t.files?.some(d=>d.storageKey===key)),post=S.posts.find(p=>p.file?.storageKey===key);if(owner&&!canLead())return toast('Tài liệu hồ sơ chỉ dành cho người quản lý được phân quyền');if(fin&&!financeAccess())return toast('Không có quyền tải chứng từ');if(training&&!currentUser())return toast('Vui lòng đăng nhập');if(post&&!visiblePost(post))return toast('Không có quyền xem thông báo');if(!owner&&!fin&&!training&&!post)return toast('Không tìm thấy tài liệu hợp lệ');oldDownload(key)};
// One reminder per unchanged balance per session, without repeated tab popups.
function showFeeReminders(){let m=currentMember();if(!m||q('#modal:not(.hide)'))return;let obs=S.obligations.filter(o=>o.memberId===m.id&&o.status!=='pending'&&debtFor(o)>0),parts=obs.map(o=>`${o.label}: ${money(debtFor(o))}, hạn ${fmtDate(o.due)}${overdueDays(o)?' — quá hạn '+overdueDays(o)+' ngày':''}`);if(m.annualDueDate){let days=Math.ceil((new Date(m.annualDueDate+'T00:00:00+07:00')-new Date())/86400000),paid=S.feePayments.some(f=>f.memberId===m.id&&f.feeType==='annual'&&f.period===m.annualDueDate.slice(0,4)&&f.status==='confirmed');if(days<=30&&!paid&&!obs.some(o=>['initial','annual'].includes(o.type)))parts.push('Tái phí thường niên: hạn '+fmtDate(m.annualDueDate))}let key='feeSeen:'+m.id+':'+parts.join('|');if(parts.length&&!sessionStorage.getItem(key)){sessionStorage.setItem(key,'1');openModal('Thông tin phí hội viên',parts.map(t=>`<p class="notice warn">${esc(t)}</p>`).join('')+'<a class="btn btn-outline" href="member-portal.html">Xem chi tiết phí của tôi</a>')}}
const oldBoot=bootV6;bootV6=function(){oldBoot();if(currentUser()&&!['lucky','login'].includes(document.body.dataset.page))setTimeout(showFeeReminders,850);if(document.body.dataset.page==='settings'&&canLead())renderAccountSettings();};
function renderAccountSettings(){q('.report-page').insertAdjacentHTML('beforeend',`<section class="panel"><h2>Tài khoản & vai trò</h2><p class="small-text">Chức danh hiển thị trên website và quyền thao tác được quản lý riêng.</p>${table(['Tài khoản','Hội viên','Vai trò','Thao tác'],S.users.map(u=>[esc(u.username),esc(memberName(u.memberId)),`<select id="role-${u.id}" ${u.id===currentUser().id?'disabled':''}>${opts(['admin','president','vice_president','secretary_lead','training_lead','guest_lead','event_lead','development_lead','orientation_lead','support_director','member'].map(r=>[r,roleLabel(r)]),u.role)}</select>`,u.id===currentUser().id?'Tài khoản đang dùng':button('Lưu quyền',`saveUserRole('${u.id}')`,'btn-outline btn-sm')]))}</section>`)}
window.saveUserRole=id=>{if(!isAdmin())return toast('Chỉ Admin được thay đổi quyền tài khoản');let u=S.users.find(u=>u.id===id);if(!u||id===currentUser().id)return;let before=u.role;u.role=val('role-'+id);auditChange('Cấp quyền tài khoản','User',before,{id,role:u.role});toast('Đã cập nhật quyền','success')};
const oldRenderLucky=renderLucky;renderLucky=function(){if(!canDept('events')){location.href='departments.html?dep=events';return}oldRenderLucky()};
for(const name of ['drawLucky','resetLucky','shuffleLucky','removeLuckyWinner']){let old=window[name];window[name]=(...args)=>{if(!canDept('events'))return toast('Chỉ Ban Sự kiện / Chủ tịch / Admin được quay thưởng');return old(...args)}}
// Normalize deduplication and exclusions per meeting, without mixing people with equal names.
eligibleLucky=function(){let mid=activeMeeting().id,seenIds=new Set(),seenPhones=new Set(),won=S.lucky.winners.filter(w=>w.meetingId===mid),removed=new Set(S.lucky.removedByMeeting?.[mid]||[]);return S.attendance.filter(a=>a.meetingId===mid).filter(a=>{let phone=(a.phone||'').replace(/[^\d+]/g,''),id=a.personId;if((id&&seenIds.has(id))||(phone&&seenPhones.has(phone))||won.some(w=>(id&&w.personKey===id)||(phone&&w.phone.replace(/[^\d+]/g,'')===phone))||removed.has(id||phone)||(!id&&!phone))return false;if(id)seenIds.add(id);if(phone)seenPhones.add(phone);return true}).map(a=>({...a,personKey:a.personId||a.phone.replace(/[^\d+]/g,'')}))};
window.removeLuckyWinner=key=>{if(!canDept('events'))return;let mid=activeMeeting().id;S.lucky.removedByMeeting??={};S.lucky.removedByMeeting[mid]??=[];if(!S.lucky.removedByMeeting[mid].includes(key))S.lucky.removedByMeeting[mid].push(key);save();renderLucky()};
// Synchronize in-memory state when another tab saves the same local store.
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{S=JSON.parse(e.newValue)}catch{}}});
const oldPostForm=window.postForm;window.postForm=dep=>{oldPostForm(dep);let field=q('#poAudience')?.parentElement;if(field)field.innerHTML='<label>Đối tượng nhận thông báo</label>'+[['all','Toàn bộ hội viên & LT'],['lt','Toàn bộ LT'],...S.departments.map(d=>[d.id,d.name])].map(([id,name])=>`<label class="inline-check"><input type="checkbox" class="postAudience" value="${id}" ${id==='all'?'checked':''}>${esc(name)}</label>`).join('')};
const originalPostSave=window.savePost;window.savePost=async(e,dep)=>{e.preventDefault();if(!qa('.postAudience:checked').length)return toast('Chọn ít nhất một nhóm nhận thông báo');await originalPostSave(e,dep)};
