(()=>{
'use strict';
const KEY='c11_erp_v5', SESSION='c11_session_v5';
const now=()=>new Date(); const iso=()=>new Date().toISOString();
const uid=(p='ID')=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const money=n=>(Number(n||0)).toLocaleString('vi-VN')+' ₫';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=s=>{if(!s)return '—';const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('vi-VN')};
const fmtDT=s=>{if(!s)return '—';const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleString('vi-VN')};
const normalizeName=s=>String(s||'').trim().toLocaleLowerCase('vi').split(/\s+/).filter(Boolean).map(w=>w.charAt(0).toLocaleUpperCase('vi')+w.slice(1)).join(' ');
const maskPhone=p=>{p=String(p||'');return p.length>=7?`${p.slice(0,4)} ••• ${p.slice(-3)}`:p};
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
function seed(){return {
 version:5,
 config:{domain:'vbna.chapter11.vn',chapter:'VBNA Chapter 11',term:{id:'NK7',name:'Nhiệm kỳ 2026–2027',start:'2026-10-01',end:'2027-09-30'},fees:{annual:3000000,monthly:500000,monthlyDueStart:1,monthlyDueEnd:10,annualAlertDays:30},anniversary:{title:'Kỷ niệm 4 năm VBNA Chapter 11',date:'2026-11-11',years:4}},
 departments:[
  {id:'president',name:'Chủ tịch',leadRole:'president',scope:'Điều hành toàn Chapter, phê duyệt hội viên, báo cáo chiến lược'},
  {id:'vice',name:'Phó chủ tịch',leadRole:'vice_president',scope:'Hỗ trợ điều hành, giám sát mục tiêu và hoạt động'},
  {id:'secretariat',name:'Ban Thư ký',leadRole:'secretary_lead',scope:'Hồ sơ, tài chính, phí, biên bản và dữ liệu'},
  {id:'training',name:'Ban Đào tạo',leadRole:'training_lead',scope:'Kế hoạch đào tạo, MSP, workshop và đánh giá'},
  {id:'guests',name:'Ban Khách mời',leadRole:'guest_lead',scope:'Khách mời, CRM, tham dự và chuyển đổi'},
  {id:'events',name:'Ban Sự kiện & Truyền thông',leadRole:'event_lead',scope:'Sự kiện, truyền thông, nội dung, sinh nhật Chapter'},
  {id:'development',name:'Ban Phát triển',leadRole:'development_lead',scope:'Power Team, ngành nghề, phát triển hội viên'},
  {id:'orientation',name:'Ban Định hướng',leadRole:'orientation_lead',scope:'Định hướng hội viên và chất lượng hoạt động'},
  {id:'support_director',name:'Giám đốc hỗ trợ',leadRole:'support_director',scope:'Hỗ trợ vận hành, phối hợp các Ban'}
 ],
 powerTeams:[
  {id:'PT-XD',name:'Xây dựng & Bất động sản',desc:'Xây dựng, nội thất, vật liệu, bất động sản'},
  {id:'PT-SK',name:'Sức khỏe & Làm đẹp',desc:'Y tế, chăm sóc sức khỏe, làm đẹp, wellness'},
  {id:'PT-DV',name:'Dịch vụ doanh nghiệp',desc:'Tài chính, pháp lý, công nghệ, marketing, tư vấn'},
  {id:'PT-TM',name:'Thương mại & Phân phối',desc:'Bán buôn, bán lẻ, sản xuất, phân phối'},
  {id:'PT-DL',name:'Du lịch & Đời sống',desc:'Du lịch, lưu trú, ẩm thực, vận tải, giáo dục'}
 ],
 users:[
  {id:'U-ADMIN',username:'admin',phone:'0900000001',email:'admin@chapter11.vn',password:'Admin123',role:'admin',memberId:null,active:true,forcePasswordChange:false},
  {id:'U-CT',username:'chutich',phone:'0900000002',email:'president@chapter11.vn',password:'ChuTich123',role:'president',memberId:'C11-0001',active:true,forcePasswordChange:false},
  {id:'U-TK',username:'thuky',phone:'0900000003',email:'secretary@chapter11.vn',password:'ThuKy123',role:'secretary_lead',memberId:'C11-0002',active:true,forcePasswordChange:false},
  {id:'U-M1',username:'0978219198',phone:'0978219198',email:'member@example.vn',password:'Member123',role:'member',memberId:'C11-0003',active:true,forcePasswordChange:true}
 ],
 members:[
  {id:'C11-0001',fullName:'Nguyễn Ngọc Soái',phone:'0900000002',email:'president@chapter11.vn',dob:'1992-05-12',homeAddress:'Hải Phòng',company:'Công ty Thành viên Chapter 11',title:'Giám đốc',businessAddress:'Hải Phòng',industry:'Giải pháp doanh nghiệp',products:'Dịch vụ doanh nghiệp',powerTeamId:'PT-DV',joinDate:'2025-10-01',admitDate:'2025-10-15',stopDate:'',stopReason:'',status:'active',departmentIds:['president'],annualDueDate:'2026-10-15',documents:[]},
  {id:'C11-0002',fullName:'Hà Thị Thu',phone:'0900000003',email:'secretary@chapter11.vn',dob:'1990-08-20',homeAddress:'Hải Phòng',company:'Doanh nghiệp Thư ký',title:'Quản lý',businessAddress:'Hải Phòng',industry:'Dịch vụ kế toán',products:'Kế toán nội bộ',powerTeamId:'PT-DV',joinDate:'2025-11-01',admitDate:'2025-11-15',stopDate:'',stopReason:'',status:'active',departmentIds:['secretariat'],annualDueDate:'2026-11-15',documents:[]},
  {id:'C11-0003',fullName:'Nguyễn Văn Anh',phone:'0978219198',email:'member@example.vn',dob:'1988-11-11',homeAddress:'Ngô Quyền, Hải Phòng',company:'Công ty Minh Anh',title:'Giám đốc',businessAddress:'Lê Hồng Phong, Hải Phòng',industry:'Nội thất',products:'Thiết kế và thi công nội thất',powerTeamId:'PT-XD',joinDate:'2026-01-10',admitDate:'2026-01-25',stopDate:'',stopReason:'',status:'active',departmentIds:['development'],annualDueDate:'2027-01-25',documents:[]},
  {id:'C11-0004',fullName:'Vũ Thị Huệ',phone:'0911222333',email:'hue@example.vn',dob:'1989-03-09',homeAddress:'Lê Chân, Hải Phòng',company:'Huệ Health',title:'Founder',businessAddress:'Hải Phòng',industry:'Chăm sóc sức khỏe',products:'Dịch vụ chăm sóc sức khỏe',powerTeamId:'PT-SK',joinDate:'2026-02-01',admitDate:'2026-02-15',stopDate:'',stopReason:'',status:'active',departmentIds:['vice'],annualDueDate:'2027-02-15',documents:[]},
  {id:'C11-0005',fullName:'Trần Tuấn Việt',phone:'0933444555',email:'viet@example.vn',dob:'1987-07-14',homeAddress:'Hải Phòng',company:'Việt Distribution',title:'Giám đốc',businessAddress:'Hải Phòng',industry:'Phân phối',products:'Phân phối hàng tiêu dùng',powerTeamId:'PT-TM',joinDate:'2026-03-01',admitDate:'2026-03-20',stopDate:'',stopReason:'',status:'active',departmentIds:['development'],annualDueDate:'2027-03-20',documents:[]}
 ],
 guests:[
  {id:'G-001',fullName:'Trần Minh Đức',phone:'0988111222',email:'duc@example.vn',address:'Hải Phòng',businessType:'Doanh nghiệp',company:'Đức Travel',industry:'Du lịch',products:'Tour doanh nghiệp',inviterId:'C11-0003',status:'attended',createdAt:'2026-09-01'},
  {id:'G-002',fullName:'Phạm Lan Anh',phone:'0977333444',email:'lananh@example.vn',address:'Hải Phòng',businessType:'HKD',company:'Lan Anh Beauty',industry:'Làm đẹp',products:'Spa',inviterId:'C11-0004',status:'contacted',createdAt:'2026-09-10'}
 ],
 meetings:[
  {id:'M-20260919',name:'Lễ Tri ân LT NK6 & Ra mắt LT NK7',date:'2026-09-19',time:'07:30',location:'Hải Phòng',termWeek:0,status:'open',publicCode:'C11-19092026'},
  {id:'M-W01',name:'Buổi họp thường tuần – Tuần 01 NK7',date:'2026-10-03',time:'07:00',location:'Hải Phòng',termWeek:1,status:'scheduled',publicCode:'C11-W01'}
 ],
 attendance:[
  {id:'AT-1',meetingId:'M-20260919',personType:'member',personId:'C11-0001',fullName:'Nguyễn Ngọc Soái',phone:'0900000002',role:'Chủ tịch Chapter 11',chapter:'11',company:'Công ty Thành viên Chapter 11',inviterId:null,checkedAt:'2026-09-19T07:00:00+07:00'},
  {id:'AT-2',meetingId:'M-20260919',personType:'member',personId:'C11-0002',fullName:'Hà Thị Thu',phone:'0900000003',role:'Ban Thư ký',chapter:'11',company:'Doanh nghiệp Thư ký',inviterId:null,checkedAt:'2026-09-19T07:03:00+07:00'},
  {id:'AT-3',meetingId:'M-20260919',personType:'member',personId:'C11-0003',fullName:'Nguyễn Văn Anh',phone:'0978219198',role:'Hội viên Chapter 11',chapter:'11',company:'Công ty Minh Anh',inviterId:null,checkedAt:'2026-09-19T07:05:00+07:00'},
  {id:'AT-4',meetingId:'M-20260919',personType:'guest',personId:'G-001',fullName:'Trần Minh Đức',phone:'0988111222',role:'Khách mời',chapter:'Khách',company:'Đức Travel',inviterId:'C11-0003',checkedAt:'2026-09-19T07:08:00+07:00'}
 ],
 opportunities:[
  {id:'OP-1',meetingId:'M-20260919',giverId:'C11-0003',receiverType:'member',receiverId:'C11-0004',receiverName:'Vũ Thị Huệ',type:'Referral cấp 1',value:12000000,status:'success',createdAt:'2026-09-19T08:00:00+07:00'},
  {id:'OP-2',meetingId:'M-20260919',giverId:'C11-0004',receiverType:'member',receiverId:'C11-0003',receiverName:'Nguyễn Văn Anh',type:'Referral cấp 2',value:25000000,status:'open',createdAt:'2026-09-19T08:05:00+07:00'},
  {id:'OP-3',meetingId:'M-20260919',giverId:'C11-0001',receiverType:'guest',receiverId:'G-001',receiverName:'Trần Minh Đức',type:'Referral cấp 1',value:8000000,status:'success',createdAt:'2026-09-19T08:09:00+07:00'}
 ],
 finance:[
  {id:'PT-2026-0001',kind:'income',category:'Phí sinh hoạt',costType:'fixed',amount:500000,memberId:'C11-0001',date:'2026-09-05',description:'Phí quỹ tháng 09/2026',status:'approved',files:[],createdBy:'U-TK'},
  {id:'PT-2026-0002',kind:'income',category:'Phí sinh hoạt',costType:'fixed',amount:500000,memberId:'C11-0002',date:'2026-09-06',description:'Phí quỹ tháng 09/2026',status:'approved',files:[],createdBy:'U-TK'},
  {id:'PC-2026-0001',kind:'expense',category:'Sự kiện',costType:'variable',amount:1800000,memberId:null,date:'2026-09-11',description:'Chi phí chuẩn bị sự kiện',status:'approved',files:['hoa-don-su-kien.pdf'],createdBy:'U-TK'},
  {id:'PC-2026-0002',kind:'expense',category:'Truyền thông',costType:'variable',amount:650000,memberId:null,date:'2026-09-13',description:'Thiết kế truyền thông',status:'pending',files:[],createdBy:'U-TK'}
 ],
 feePayments:[
  {id:'FP-1',memberId:'C11-0001',feeType:'monthly',period:'2026-09',amount:500000,status:'confirmed',confirmedAt:'2026-09-05',financeId:'PT-2026-0001'},
  {id:'FP-2',memberId:'C11-0002',feeType:'monthly',period:'2026-09',amount:500000,status:'confirmed',confirmedAt:'2026-09-06',financeId:'PT-2026-0002'}
 ],
 events:[{id:'EV-ANN-2026',title:'Kỷ niệm 4 năm VBNA Chapter 11',date:'2026-11-11',departmentId:'events',priority:'high',description:'Chuẩn bị chương trình sinh nhật Chapter 11 tròn 4 năm.',status:'planning'}],
 vbnaPeople:[
  {id:'P-HDSL-01',group:'HĐSL',fullName:'Thành viên HĐSL mẫu',phone:'0901000001',email:'hdsl@example.vn',company:'VBNA',industry:'Điều hành',chapter:'VBNA',department:''},
  {id:'P-HDTV-01',group:'HĐTV',fullName:'Thành viên HĐTV mẫu',phone:'0901000002',email:'hdtv@example.vn',company:'VBNA',industry:'Điều hành',chapter:'VBNA',department:''},
  {id:'P-CT-01',group:'Chủ tịch Chapter',fullName:'Chủ tịch Chapter 01',phone:'0901000003',email:'chapter1@example.vn',company:'Doanh nghiệp Chapter 01',industry:'Doanh nghiệp',chapter:'01',department:'Chủ tịch'},
  {id:'P-LT-01',group:'LT Chapter',fullName:'Thành viên LT Chapter 02',phone:'0901000004',email:'lt2@example.vn',company:'Doanh nghiệp Chapter 02',industry:'Dịch vụ',chapter:'02',department:'Ban Đào tạo'}
 ],
 approvals:[],
 audit:[{id:'AU-1',time:'2026-09-15T20:00:00+07:00',userId:'U-ADMIN',action:'Khởi tạo hệ thống',entity:'System',detail:'ERP Chapter 11 V5'}],
 supportTickets:[],
 mailOutbox:[],
 lucky:{winners:[],removedIds:[],shuffleSeed:0}
}}
function load(){let raw=localStorage.getItem(KEY);if(!raw){let s=seed();localStorage.setItem(KEY,JSON.stringify(s));return s}try{let s=JSON.parse(raw);if(s.version!==5){let n=seed();localStorage.setItem(KEY,JSON.stringify(n));return n}return s}catch{let s=seed();localStorage.setItem(KEY,JSON.stringify(s));return s}}
let S=load();
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function currentUser(){let x=session();return x?S.users.find(u=>u.id===x.userId&&u.active):null}
function currentMember(){let u=currentUser();return u?.memberId?S.members.find(m=>m.id===u.memberId):null}
function log(action,entity,detail=''){let u=currentUser();S.audit.unshift({id:uid('AU'),time:iso(),userId:u?.id||'PUBLIC',action,entity,detail});S.audit=S.audit.slice(0,400);save()}
function isAdmin(u=currentUser()){return !!u&&u.role==='admin'}
function canManageDepartment(depId,u=currentUser()){if(!u)return false;if(u.role==='admin'||u.role==='president')return true;let d=S.departments.find(x=>x.id===depId);if(!d)return false;if(u.role===d.leadRole)return true;let m=u.memberId&&S.members.find(x=>x.id===u.memberId);return !!m?.departmentIds?.includes(depId)}
function requireAuth(){if(!currentUser()){location.href='login.html?next='+encodeURIComponent(location.pathname.split('/').pop()+location.hash);return false}return true}
function activeMeeting(){return S.meetings.find(m=>m.status==='open')||S.meetings.find(m=>new Date(m.date)>=new Date().setHours(0,0,0,0))||S.meetings[0]}
function memberName(id){return S.members.find(m=>m.id===id)?.fullName||'—'}
function powerName(id){return S.powerTeams.find(p=>p.id===id)?.name||'—'}
function userName(id){let u=S.users.find(x=>x.id===id);return u?.memberId?memberName(u.memberId):(u?.username||id||'—')}
function toast(msg,type=''){let st=q('.toast-stack');if(!st){st=document.createElement('div');st.className='toast-stack';document.body.append(st)}let el=document.createElement('div');el.className='toast';if(type==='success')el.style.borderLeftColor='#18794e';el.innerHTML=`<strong>${type==='success'?'Thành công':'Thông báo'}</strong>${esc(msg)}`;st.append(el);setTimeout(()=>el.remove(),3500)}
window.toast=toast;
function openModal(title,html){let b=q('#modal'); if(!b){b=document.createElement('div');b.id='modal';b.className='modal-backdrop';b.innerHTML='<div class="modal"><button class="modal-close" onclick="closeModal()">Đóng</button><h2 id="modalTitle"></h2><div id="modalBody"></div></div>';document.body.append(b)}q('#modalTitle',b).textContent=title;q('#modalBody',b).innerHTML=html;b.classList.remove('hide')}
window.closeModal=()=>q('#modal')?.classList.add('hide');
function fileMeta(input,max=10){return [...(input?.files||[])].slice(0,max).map(f=>({name:f.name,size:f.size,type:f.type,lastModified:f.lastModified}))}
function openFileDB(){return new Promise((resolve,reject)=>{let req=indexedDB.open('c11_erp_files_v5',1);req.onupgradeneeded=()=>{let db=req.result;if(!db.objectStoreNames.contains('files'))db.createObjectStore('files',{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function persistInputFiles(input,max=10,group='other'){let fs=[...(input?.files||[])].slice(0,max),out=[];if(!fs.length)return out;try{let db=await openFileDB();for(let f of fs){let key=uid('FILE');await new Promise((res,rej)=>{let tx=db.transaction('files','readwrite');tx.objectStore('files').put({key,blob:f,name:f.name,type:f.type,size:f.size,group,createdAt:iso()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});out.push({storageKey:key,name:f.name,size:f.size,type:f.type,typeGroup:group,lastModified:f.lastModified})}db.close();return out}catch(e){console.warn('IndexedDB file fallback',e);return fs.map(f=>({name:f.name,size:f.size,type:f.type,typeGroup:group,lastModified:f.lastModified}))}}
window.downloadStoredFile=async key=>{try{let db=await openFileDB();let obj=await new Promise((res,rej)=>{let tx=db.transaction('files','readonly');let r=tx.objectStore('files').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();if(!obj)return toast('Không tìm thấy file trong bộ nhớ trình duyệt');let url=URL.createObjectURL(obj.blob),a=document.createElement('a');a.href=url;a.download=obj.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{toast('Không thể mở file đã lưu')}}

function validPassword(p){return /[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&p.length>=8}
function generatePassword(){const A='ABCDEFGHJKLMNPQRSTUVWXYZ',a='abcdefghijkmnopqrstuvwxyz',n='23456789';let p=A[Math.floor(Math.random()*A.length)]+a[Math.floor(Math.random()*a.length)]+n[Math.floor(Math.random()*n.length)];let all=A+a+n;while(p.length<10)p+=all[Math.floor(Math.random()*all.length)];return p.split('').sort(()=>Math.random()-.5).join('')}
function queueMail(to,subject,body){S.mailOutbox.unshift({id:uid('MAIL'),to,subject,body,createdAt:iso(),status:'queued'});save()}
function updateMeetingText(){let m=activeMeeting();qa('[data-meeting-name]').forEach(e=>e.textContent=m.name);qa('[data-meeting-meta]').forEach(e=>e.textContent=`${fmtDate(m.date)} • ${m.time} • ${m.location}`)}
function bindAdminLinks(){qa('.side-link[data-section]').forEach(a=>a.onclick=e=>{e.preventDefault();showAdminSection(a.dataset.section)})}
function statusChip(v){const map={active:['green','Đang hoạt động'],inactive:['gray','Không hoạt động'],pending:['gold','Chờ duyệt'],approved:['green','Đã duyệt'],confirmed:['green','Đã xác nhận'],open:['blue','Đang xử lý'],success:['green','Thành công'],scheduled:['blue','Đã lên lịch'],contacted:['blue','Đã liên hệ'],attended:['green','Đã tham dự'],planning:['gold','Đang chuẩn bị']};let x=map[v]||['gray',v||'—'];return `<span class="chip ${x[0]}">${esc(x[1])}</span>`}
function renderHome(){
 const active=S.members.filter(m=>m.status==='active'); let ops=S.opportunities; let m=activeMeeting();
 q('#homeMemberCount')&&(q('#homeMemberCount').textContent=active.length);q('#homeOppCount')&&(q('#homeOppCount').textContent=ops.length);q('#homeOppValue')&&(q('#homeOppValue').textContent=money(ops.reduce((a,b)=>a+b.value,0)).replace(' ₫',''));
 q('#nextMeetingName')&&(q('#nextMeetingName').textContent=m.name);q('#nextMeetingMeta')&&(q('#nextMeetingMeta').textContent=`${fmtDate(m.date)} • ${m.time} • ${m.location}`);
 let leaders=S.departments.slice(0,4).map(d=>{let mem=S.members.find(m=>m.departmentIds?.includes(d.id));return `<article class="card member-card"><div class="member-top"><div class="member-avatar">${esc(mem?.fullName?.split(' ').slice(-1)[0]?.[0]||'C')}</div><div><h3>${esc(mem?.fullName||'Đang cập nhật')}</h3><small>${esc(d.name)}</small></div></div><p>${esc(mem?.company||d.scope)}</p></article>`}).join('');q('#publicLeaders')&&(q('#publicLeaders').innerHTML=leaders);
 q('#publicPowerTeams')&&(q('#publicPowerTeams').innerHTML=S.powerTeams.slice(0,4).map(p=>`<article class="card power-card"><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><span class="chip red">${S.members.filter(m=>m.powerTeamId===p.id&&m.status==='active').length} hội viên</span></article>`).join(''));
 q('#publicDirectory')&&(q('#publicDirectory').innerHTML=active.slice(0,6).map(m=>memberCard(m)).join(''));
}
function memberCard(m){return `<article class="card member-card"><div class="member-top"><div class="member-avatar">${esc(m.fullName.split(' ').slice(-1)[0][0])}</div><div><h3>${esc(m.fullName)}</h3><small>${esc(m.industry)}</small></div></div><p><b>${esc(m.company)}</b><br>${esc(m.products)}</p><div class="member-meta"><span class="chip red">${esc(powerName(m.powerTeamId))}</span></div></article>`}
function renderPublicMembersPage(){let term=(q('#publicMemberSearch')?.value||'').toLowerCase();let pt=q('#publicPowerFilter')?.value||'';let list=S.members.filter(m=>m.status==='active'&&(!pt||m.powerTeamId===pt)&&(!term||[m.fullName,m.company,m.industry,m.products].join(' ').toLowerCase().includes(term)));q('#membersPublicGrid')&&(q('#membersPublicGrid').innerHTML=list.map(memberCard).join('')||'<div class="empty">Không có kết quả</div>');q('#membersPublicLeaders')&&(q('#membersPublicLeaders').innerHTML=S.departments.slice(0,9).map(d=>{let m=S.members.find(x=>x.departmentIds?.includes(d.id));return `<article class="card"><div class="eyebrow">${esc(d.name)}</div><h3>${esc(m?.fullName||'Đang cập nhật')}</h3><p>${esc(m?.company||d.scope)}</p></article>`}).join(''));let sel=q('#publicPowerFilter');if(sel&&sel.options.length===1)S.powerTeams.forEach(p=>sel.add(new Option(p.name,p.id)))}
window.renderPublicMembersPage=renderPublicMembersPage;
function renderPowerTeams(){let el=q('#powerTeamPublic');if(el)el.innerHTML=S.powerTeams.map(p=>`<article class="card power-card"><div class="eyebrow">Power Team</div><h2>${esc(p.name)}</h2><p>${esc(p.desc)}</p><div class="member-meta">${S.members.filter(m=>m.powerTeamId===p.id&&m.status==='active').map(m=>`<span class="chip red">${esc(m.fullName)}</span>`).join('')||'<span class="chip gray">Chưa có hội viên</span>'}</div></article>`).join('')}
function renderMeetingPage(){let m=activeMeeting();q('#meetingDate')&&(q('#meetingDate').textContent=fmtDate(m.date));q('#meetingTime')&&(q('#meetingTime').textContent=m.time);q('#meetingLocation')&&(q('#meetingLocation').textContent=m.location);let at=S.attendance.filter(a=>a.meetingId===m.id);q('#meetingAttendance')&&(q('#meetingAttendance').textContent=at.length)}
function fillMemberSelect(el,includeGuests=false){if(!el)return;el.innerHTML='<option value="">-- Chọn --</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="M:${m.id}">${esc(m.fullName)} • ${esc(m.industry)}</option>`).join('')+(includeGuests?S.guests.filter(g=>['attended','contacted'].includes(g.status)).map(g=>`<option value="G:${g.id}">${esc(g.fullName)} • Khách mời</option>`).join(''):'')}
function renderCheckin(){let t=q('#checkinType');if(t)checkinTypeChanged();let inv=q('#inviterId');if(inv){inv.innerHTML='<option value="">Không có / không nhớ</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="${m.id}">${esc(m.fullName)}</option>`).join('')}}
window.checkinTypeChanged=()=>{let t=q('#checkinType')?.value;let memberBox=q('#memberCheckinBox'),guestBox=q('#guestCheckinBox');if(memberBox)memberBox.classList.toggle('hide',t!=='chapter11');if(guestBox)guestBox.classList.toggle('hide',t==='chapter11');if(t==='chapter11'){let sel=q('#checkinMemberId');if(sel)sel.innerHTML='<option value="">-- Chọn hội viên --</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="${m.id}">${esc(m.fullName)} • ${esc(m.company)}</option>`).join('')}};
window.submitCheckin=e=>{e.preventDefault();let m=activeMeeting(),type=q('#checkinType').value, rec;if(type==='chapter11'){let id=q('#checkinMemberId').value,mem=S.members.find(x=>x.id===id);if(!mem)return toast('Vui lòng chọn hội viên');rec={personType:'member',personId:mem.id,fullName:mem.fullName,phone:mem.phone,role:'Hội viên Chapter 11',chapter:'11',company:mem.company,inviterId:null}}else{let name=normalizeName(q('#guestName')?.value),phone=q('#guestPhone')?.value.trim();if(!name||!phone)return toast('Vui lòng nhập họ tên và số điện thoại');rec={personType:'guest',personId:'',fullName:name,phone,role:q('#guestRole')?.value||'Khách mời',chapter:q('#guestChapter')?.value||'Khách',company:q('#guestCompany')?.value||'',inviterId:q('#inviterId')?.value||null}}let dup=S.attendance.find(a=>a.meetingId===m.id&&((rec.personId&&a.personId===rec.personId)||(rec.phone&&a.phone===rec.phone)));if(dup)return toast('Người này đã điểm danh trong buổi họp');if(rec.personType==='guest'){let g=S.guests.find(x=>x.phone===rec.phone);if(!g){g={id:uid('G'),fullName:rec.fullName,phone:rec.phone,email:'',address:'',businessType:'',company:rec.company,industry:'',products:'',inviterId:rec.inviterId,status:'attended',createdAt:iso()};S.guests.push(g)}else g.status='attended';rec.personId=g.id}S.attendance.push({id:uid('AT'),meetingId:m.id,...rec,checkedAt:iso()});save();log('Điểm danh','Attendance',`${rec.fullName} • ${m.name}`);q('#checkinSuccess')?.classList.remove('hide');e.target.reset();renderCheckin();toast('Điểm danh thành công','success')};
function renderGuestRegister(){let inv=q('#guestInviter');if(inv)inv.innerHTML='<option value="">Không có</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="${m.id}">${esc(m.fullName)}</option>`).join('');toggleCompanyFields()}
window.toggleCompanyFields=()=>{let t=q('#businessType')?.value;qa('[data-company-field]').forEach(x=>x.classList.toggle('hide',t==='Cá nhân'))};
window.submitGuest=e=>{e.preventDefault();let phone=q('#guestRegPhone').value.trim();if(S.guests.some(g=>g.phone===phone))return toast('Số điện thoại này đã có trong CRM');let g={id:uid('G'),fullName:normalizeName(q('#guestRegName').value),phone,email:q('#guestRegEmail').value.trim(),address:q('#guestRegAddress').value.trim(),businessType:q('#businessType').value,company:q('#guestRegCompany')?.value.trim()||'',industry:q('#guestRegIndustry').value.trim(),products:q('#guestRegProducts').value.trim(),inviterId:q('#guestInviter')?.value||null,status:'new',createdAt:iso()};S.guests.push(g);save();log('Đăng ký khách mời','Guest',g.fullName);q('#guestRegSuccess')?.classList.remove('hide');e.target.reset();renderGuestRegister();toast('Đã gửi thông tin. Ban Khách mời sẽ liên hệ.','success')};
function renderOpportunity(){let giver=q('#giverId');if(giver)giver.innerHTML='<option value="">-- Chọn hội viên --</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="${m.id}">${esc(m.fullName)}</option>`).join('');let rows=q('#opportunityRows');if(rows&&!rows.children.length)addOpportunityRow()}
window.addOpportunityRow=()=>{let tb=q('#opportunityRows');if(!tb)return;let tr=document.createElement('tr');tr.innerHTML=`<td><select class="oppReceiver" required><option value="">-- Chọn --</option>${S.members.filter(m=>m.status==='active').map(m=>`<option value="M:${m.id}">${esc(m.fullName)} • Hội viên</option>`).join('')}${S.guests.filter(g=>['attended','contacted'].includes(g.status)).map(g=>`<option value="G:${g.id}">${esc(g.fullName)} • Khách mời</option>`).join('')}</select></td><td><select class="oppType"><option>Referral cấp 1</option><option>Referral cấp 2</option><option>Referral cấp 3</option><option>Referral cấp 4</option><option>Referral cấp 5</option><option>Dance 1-2-1</option><option>Cảm ơn đã nhận cơ hội</option></select></td><td><input class="oppValue" type="number" min="0" step="1000" value="0"></td><td><button type="button" class="btn btn-soft btn-sm" onclick="this.closest('tr').remove()">Xóa</button></td>`;tb.append(tr)};
window.submitOpportunity=e=>{e.preventDefault();let giverId=q('#giverId').value;if(!giverId)return toast('Chọn người trao');let rows=qa('#opportunityRows tr');if(!rows.length)return toast('Cần ít nhất một dòng cơ hội');let m=activeMeeting(),added=0;for(let tr of rows){let rv=q('.oppReceiver',tr)?.value;if(!rv)continue;let [kind,id]=rv.split(':');let obj=kind==='M'?S.members.find(x=>x.id===id):S.guests.find(x=>x.id===id);S.opportunities.push({id:uid('OP'),meetingId:m.id,giverId,receiverType:kind==='M'?'member':'guest',receiverId:id,receiverName:obj?.fullName||'',type:q('.oppType',tr).value,value:Number(q('.oppValue',tr).value||0),status:'open',createdAt:iso()});added++}save();log('Trao cơ hội','Opportunity',`${memberName(giverId)} • ${added} cơ hội`);q('#oppSuccess')?.classList.remove('hide');q('#opportunityRows').innerHTML='';addOpportunityRow();toast(`Đã ghi nhận ${added} cơ hội`,'success')};
function homeForUser(u){if(!u)return 'login.html';if(['admin','president'].includes(u.role))return 'admin.html';let map={secretary_lead:'secretariat',vice_president:'vice',training_lead:'training',guest_lead:'guests',event_lead:'events',development_lead:'development',orientation_lead:'orientation',support_director:'support_director'};if(map[u.role])return 'departments.html?dep='+map[u.role];return 'member-portal.html'}
function roleLabel(r){return ({admin:'Admin',president:'Chủ tịch',vice_president:'Phó chủ tịch',secretary_lead:'Trưởng ban Thư ký',training_lead:'Trưởng ban Đào tạo',guest_lead:'Trưởng ban Khách mời',event_lead:'Trưởng ban Sự kiện & Truyền thông',development_lead:'Trưởng ban Phát triển',orientation_lead:'Trưởng ban Định hướng',support_director:'Giám đốc hỗ trợ',member:'Hội viên'})[r]||r}
window.login=e=>{e.preventDefault();let u0=q('#loginUser').value.trim(),p=q('#loginPass').value;let u=S.users.find(x=>x.active&&(x.username===u0||x.phone===u0)&&x.password===p);if(!u)return toast('Sai tài khoản, mật khẩu hoặc tài khoản đang bị khóa');localStorage.setItem(SESSION,JSON.stringify({userId:u.id,loginAt:iso()}));log('Đăng nhập','Auth',u.username);if(u.forcePasswordChange){showForcePassword(u)}else{let params=new URLSearchParams(location.search);location.href=params.get('next')||homeForUser(u)}};
function showForcePassword(u){openModal('Đổi mật khẩu lần đầu',`<div class="notice warn">Mật khẩu phải tối thiểu 8 ký tự, gồm chữ hoa, chữ thường và số.</div><div class="field" style="margin-top:14px"><label>Mật khẩu mới</label><input id="newPassword" type="password"></div><div class="field" style="margin-top:12px"><label>Nhập lại mật khẩu</label><input id="newPassword2" type="password"></div><button class="btn btn-wine" style="margin-top:14px;width:100%" onclick="completePasswordChange('${u.id}')">Đổi mật khẩu</button>`)}
window.completePasswordChange=id=>{let p=q('#newPassword').value,p2=q('#newPassword2').value;if(p!==p2)return toast('Hai mật khẩu không giống nhau');if(!validPassword(p))return toast('Mật khẩu chưa đạt yêu cầu');let u=S.users.find(x=>x.id===id);u.password=p;u.forcePasswordChange=false;save();queueMail(u.email,'Đổi mật khẩu thành công',`Mật khẩu tài khoản ${u.username} đã được thay đổi thành công.`);log('Đổi mật khẩu','User',u.username);location.href=homeForUser(u)};
function logout(){localStorage.removeItem(SESSION);location.href='login.html'} window.logout=logout;
function renderAdmin(){if(!requireAuth())return;let u=currentUser();if(!['admin','president'].includes(u.role)){location.href='departments.html';return}bindAdminLinks();q('#adminUser')&&(q('#adminUser').textContent=(currentMember()?.fullName||u.username).split(' ').slice(-1)[0].slice(0,2).toUpperCase());let wanted=location.hash.replace('#','')||'dashboard';showAdminSection(wanted);showAlerts();}
function showAlerts(){let u=currentUser();if(!u)return;let m=currentMember();let alerts=[];if(m){let mo=new Date().toISOString().slice(0,7);let day=new Date().getDate();let monthly=S.feePayments.some(f=>f.memberId===m.id&&f.feeType==='monthly'&&f.period===mo&&f.status==='confirmed');if(day>=S.config.fees.monthlyDueStart&&!monthly)alerts.push(day<=S.config.fees.monthlyDueEnd?`Phí quỹ tháng ${mo}: ${money(S.config.fees.monthly)}. Hạn nộp từ ngày 01–10.`:`Phí quỹ tháng ${mo}: ${money(S.config.fees.monthly)} đã quá hạn ngày 10 và chưa được Ban Thư ký xác nhận.`);let due=new Date(m.annualDueDate),days=Math.ceil((due-new Date())/86400000);let paid=S.feePayments.some(f=>f.memberId===m.id&&f.feeType==='annual'&&f.period===m.annualDueDate.slice(0,4)&&f.status==='confirmed');if(days<=S.config.fees.annualAlertDays&&!paid)alerts.push(days>=0?`Phí thường niên ${money(S.config.fees.annual)} sẽ đến hạn ngày ${fmtDate(m.annualDueDate)} (${days} ngày nữa).`:`Phí thường niên ${money(S.config.fees.annual)} đã quá hạn ${Math.abs(days)} ngày và chưa được xác nhận.`)}let ev=S.events.find(e=>e.id==='EV-ANN-2026');if(ev&&['admin','president','event_lead'].includes(u.role)){let d=Math.ceil((new Date(ev.date)-new Date())/86400000);if(d>=0&&d<=90)alerts.push(`${ev.title} ngày ${fmtDate(ev.date)} còn ${d} ngày. Ban Sự kiện & Truyền thông cần cập nhật kế hoạch.`)}if(alerts.length){setTimeout(()=>openModal('Cảnh báo Chapter 11',alerts.map(a=>`<div class="notice warn" style="margin-bottom:10px">${esc(a)}</div>`).join('')),250)}}
window.showAdminSection=sec=>{if(!requireAuth())return;if(sec==='settings'&&!isAdmin()){toast('Cấu hình hệ thống chỉ dành cho Admin cao nhất');sec='dashboard'}qa('.content-section').forEach(s=>s.classList.add('hide'));let target=q('#section-'+sec)||q('#section-dashboard');target?.classList.remove('hide');qa('.side-link[data-section]').forEach(a=>a.classList.toggle('active',a.dataset.section===sec));q('#adminTitle')&&(q('#adminTitle').textContent=({dashboard:'Dashboard điều hành',members:'Quản lý hội viên',guests:'Khách mời & CRM','vbna-people':'Danh mục VBNA',meetings:'Cuộc họp & Điểm danh',opportunities:'Cơ hội & Referral',finance:'Tài chính – Thu chi',fees:'Phí hội viên',documents:'Kho chứng từ',leadership:'Leader Team & các Ban',powerteams:'Power Team & Ngành nghề',reports:'Báo cáo nhiệm kỳ',approvals:'Phê duyệt & Nhật ký',settings:'Cấu hình hệ thống'})[sec]||'Dashboard');history.replaceState(null,'','#'+sec);renderAdminSection(sec)};
function renderAdminSection(sec){({dashboard:renderDashboard,members:renderMembers,guests:renderGuests,'vbna-people':renderVbnaPeople,meetings:renderMeetings,opportunities:renderOpportunityDashboard,finance:renderFinance,fees:renderFees,documents:renderDocuments,leadership:renderLeadership,powerteams:renderPowerTeamsAdmin,reports:renderReports,approvals:renderApprovals,settings:renderSettings})[sec]?.()}
function renderDashboard(){let m=activeMeeting(),active=S.members.filter(x=>x.status==='active'),at=S.attendance.filter(x=>x.meetingId===m.id),ops=S.opportunities,fin=S.finance.filter(x=>x.status==='approved'),bal=fin.reduce((a,x)=>a+(x.kind==='income'?x.amount:-x.amount),0);q('#kpiMembers').textContent=active.length;q('#kpiAttendance').textContent=(active.length?Math.round(at.filter(x=>x.personType==='member').length/active.length*100):0)+'%';q('#kpiOpps').textContent=ops.length;q('#kpiOppValue').textContent=money(ops.reduce((a,b)=>a+b.value,0));q('#kpiFund').textContent=money(bal);q('#kpiGuests').textContent=S.guests.length;let al=[];let pending=S.approvals.filter(a=>a.status==='pending').length;if(pending)al.push(`<div class="notice warn">${pending} yêu cầu đang chờ phê duyệt.</div>`);let noDocs=S.finance.filter(f=>f.kind==='expense'&&f.status!=='cancelled'&&!(f.files||[]).length).length;if(noDocs)al.push(`<div class="notice danger">${noDocs} khoản chi chưa có chứng từ.</div>`);q('#dashboardAlerts').innerHTML=al.join('')||'<div class="notice success">Không có cảnh báo vận hành quan trọng.</div>';let rank=rankPeople('giver');q('#topOpportunity').innerHTML=rank.slice(0,5).map((r,i)=>`<div class="metric-row"><span>${i+1}. ${esc(r.name)}</span><b>${r.count} phiếu • ${money(r.value)}</b></div>`).join('');let stages=['new','contacted','attended','interested','application','approved'];q('#guestFunnel').innerHTML=stages.map(st=>`<div class="metric-row"><span>${({new:'Mới đăng ký',contacted:'Đã liên hệ',attended:'Đã tham dự',interested:'Quan tâm hội viên',application:'Đang làm hồ sơ',approved:'Đã kết nạp'})[st]}</span><b>${S.guests.filter(g=>g.status===st).length}</b></div>`).join('')}
function renderMembers(){let term=(q('#memberSearch')?.value||'').toLowerCase(),st=q('#memberStatusFilter')?.value||'';let list=S.members.filter(m=>(!st||m.status===st)&&(!term||[m.fullName,m.phone,m.company,m.industry,m.id].join(' ').toLowerCase().includes(term)));q('#membersTable').innerHTML=list.map(m=>`<tr><td><b>${esc(m.fullName)}</b><br><small>${esc(m.id)} • ${esc(m.phone)}</small></td><td>${esc(m.company)}<br><small>${esc(m.industry)}</small></td><td>${esc(powerName(m.powerTeamId))}</td><td>${fmtDate(m.admitDate)}</td><td>${statusChip(m.status)}</td><td><button class="btn btn-soft btn-sm" onclick="viewMember('${m.id}')">Chi tiết</button> <button class="btn btn-outline btn-sm" onclick="editMember('${m.id}')">Sửa</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Không có dữ liệu</td></tr>'}
window.renderMembers=renderMembers;
window.viewMember=id=>{let m=S.members.find(x=>x.id===id);if(!m)return;let u=S.users.find(x=>x.memberId===id);openModal('Hồ sơ hội viên',`<div class="detail-list"><div class="detail-item"><small>Họ tên</small><strong>${esc(m.fullName)}</strong></div><div class="detail-item"><small>SĐT / Email</small><strong>${esc(m.phone)} • ${esc(m.email)}</strong></div><div class="detail-item"><small>Địa chỉ nhà riêng</small><strong>${esc(m.homeAddress)}</strong></div><div class="detail-item"><small>Doanh nghiệp</small><strong>${esc(m.company)}</strong></div><div class="detail-item"><small>Địa chỉ kinh doanh</small><strong>${esc(m.businessAddress)}</strong></div><div class="detail-item"><small>Ngành nghề</small><strong>${esc(m.industry)}</strong></div><div class="detail-item"><small>Power Team</small><strong>${esc(powerName(m.powerTeamId))}</strong></div><div class="detail-item"><small>Ngày gia nhập / kết nạp</small><strong>${fmtDate(m.joinDate)} / ${fmtDate(m.admitDate)}</strong></div><div class="detail-item"><small>Trạng thái tài khoản</small><strong>${u?.active?'Đang mở':'Chưa có / đã khóa'}</strong></div><div class="detail-item"><small>Tài liệu</small><strong>${(m.documents||[]).length} file</strong></div><div class="detail-item"><small>Ngày dừng / Lý do</small><strong>${fmtDate(m.stopDate)} • ${esc(m.stopReason||'—')}</strong></div></div><div class="toolbar" style="margin-top:16px;flex-wrap:wrap"><button class="btn btn-outline" onclick="requestMemberStatus('${id}','paused')">Tạm dừng</button><button class="btn btn-outline" onclick="requestMemberStatus('${id}','left')">Rời Chapter</button><button class="btn btn-danger" onclick="requestMemberStatus('${id}','terminated')">Chấm dứt tư cách</button>${m.status!=='active'?`<button class="btn btn-soft" onclick="applyMemberStatus('${id}','active')">Khôi phục hội viên</button>`:''}${u?`<button class="btn btn-soft" onclick="toggleMemberAccount('${id}')">${u.active?'Khóa tài khoản':'Mở tài khoản'}</button><button class="btn btn-soft" onclick="resetMemberPassword('${id}')">Reset mật khẩu</button>`:''}</div>`)};
window.editMember=id=>memberForm(S.members.find(x=>x.id===id));window.addMember=()=>memberForm(null);
function memberForm(m){let isNew=!m;openModal(isNew?'Thêm hồ sơ hội viên':'Cập nhật hội viên',`<form id="memberForm" onsubmit="saveMember(event,'${m?.id||''}')"><div class="form-grid"><div class="field"><label>Họ tên *</label><input id="mfName" required value="${esc(m?.fullName||'')}"></div><div class="field"><label>Số điện thoại *</label><input id="mfPhone" required value="${esc(m?.phone||'')}"></div><div class="field"><label>Email *</label><input id="mfEmail" type="email" required value="${esc(m?.email||'')}"></div><div class="field"><label>Ngày sinh</label><input id="mfDob" type="date" value="${esc(m?.dob||'')}"></div><div class="field"><label>Địa chỉ nhà riêng</label><input id="mfHome" value="${esc(m?.homeAddress||'')}"></div><div class="field"><label>Tên doanh nghiệp/HKD</label><input id="mfCompany" value="${esc(m?.company||'')}"></div><div class="field"><label>Chức vụ</label><input id="mfTitle" value="${esc(m?.title||'')}"></div><div class="field"><label>Địa chỉ kinh doanh</label><input id="mfBusinessAddress" value="${esc(m?.businessAddress||'')}"></div><div class="field"><label>Ngành nghề</label><input id="mfIndustry" value="${esc(m?.industry||'')}"></div><div class="field"><label>Sản phẩm/Dịch vụ</label><input id="mfProducts" value="${esc(m?.products||'')}"></div><div class="field"><label>Power Team</label><select id="mfPower">${S.powerTeams.map(p=>`<option value="${p.id}" ${m?.powerTeamId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Ngày gia nhập</label><input id="mfJoin" type="date" value="${esc(m?.joinDate||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Ngày kết nạp</label><input id="mfAdmit" type="date" value="${esc(m?.admitDate||'')}"></div><div class="field"><label>Hạn phí thường niên</label><input id="mfAnnualDue" type="date" value="${esc(m?.annualDueDate||'')}"></div></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Ảnh GPLKD</label><input id="mfLicense" type="file" accept="image/*,.pdf"></div><div class="field"><label>Ảnh CCCD</label><input id="mfIdCard" type="file" accept="image/*,.pdf"></div><div class="field"><label>Ảnh mặt tiền cửa hàng/doanh nghiệp</label><input id="mfFront" type="file" accept="image/*"></div><div class="field"><label>File khác (tối đa 10)</label><input id="mfOther" type="file" multiple></div></div><div class="notice" style="margin-top:12px">CCCD và giấy phép kinh doanh là dữ liệu nhạy cảm: chỉ Admin, Chủ tịch và người được phân quyền hồ sơ mới được xem.</div><button class="btn btn-wine" style="margin-top:16px">${isNew?'Tạo hồ sơ & gửi duyệt':'Lưu thay đổi'}</button></form>`)}
window.saveMember=async(e,id)=>{e.preventDefault();let existing=id&&S.members.find(x=>x.id===id);let docs=[...(await persistInputFiles(q('#mfLicense'),1,'license')),...(await persistInputFiles(q('#mfIdCard'),1,'idcard')),...(await persistInputFiles(q('#mfFront'),1,'front')),...(await persistInputFiles(q('#mfOther'),10,'other'))];let obj={id:existing?.id||`C11-${String(S.members.length+1).padStart(4,'0')}`,fullName:normalizeName(q('#mfName').value),phone:q('#mfPhone').value.trim(),email:q('#mfEmail').value.trim(),dob:q('#mfDob').value,homeAddress:q('#mfHome').value.trim(),company:q('#mfCompany').value.trim(),title:q('#mfTitle').value.trim(),businessAddress:q('#mfBusinessAddress').value.trim(),industry:q('#mfIndustry').value.trim(),products:q('#mfProducts').value.trim(),powerTeamId:q('#mfPower').value,joinDate:q('#mfJoin').value,admitDate:q('#mfAdmit').value,annualDueDate:q('#mfAnnualDue').value,stopDate:existing?.stopDate||'',stopReason:existing?.stopReason||'',status:existing?.status||'pending',departmentIds:existing?.departmentIds||[],documents:[...(existing?.documents||[]),...docs]};if(existing)Object.assign(existing,obj);else{S.members.push(obj);S.approvals.unshift({id:uid('APR'),type:'member_admission',entityId:obj.id,title:`Kết nạp ${obj.fullName}`,status:'pending',requestedBy:currentUser()?.id||'PUBLIC',createdAt:iso()})}save();log(existing?'Cập nhật hội viên':'Tạo hồ sơ hội viên','Member',obj.fullName);closeModal();renderMembers();toast(existing?'Đã lưu hồ sơ':'Đã tạo hồ sơ và gửi chờ duyệt','success')};
window.requestMemberStatus=(id,status)=>{let m=S.members.find(x=>x.id===id);openModal('Thay đổi trạng thái hội viên',`<div class="notice warn">Nghiệp vụ này được lưu lịch sử và có thể làm khóa tài khoản đăng nhập.</div><div class="field" style="margin-top:14px"><label>Trạng thái</label><select id="msStatus"><option value="paused" ${status==='paused'?'selected':''}>Tạm dừng</option><option value="left" ${status==='left'?'selected':''}>Rời Chapter</option><option value="terminated" ${status==='terminated'?'selected':''}>Chấm dứt tư cách</option></select></div><div class="field" style="margin-top:12px"><label>Lý do *</label><textarea id="msReason" required></textarea></div><div class="field" style="margin-top:12px"><label>Quyết định / Văn bản đính kèm</label><input id="msDecision" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></div><button class="btn btn-wine" style="margin-top:14px;width:100%" onclick="submitMemberStatusChange('${id}')">Xác nhận</button>`)};
window.submitMemberStatusChange=async id=>{let status=q('#msStatus').value,reason=q('#msReason').value.trim();if(!reason)return toast('Vui lòng nhập lý do');let docs=await persistInputFiles(q('#msDecision'),1,'decision');if(!['admin','president'].includes(currentUser()?.role)){S.approvals.unshift({id:uid('APR'),type:'member_status',entityId:id,targetStatus:status,title:`Đổi trạng thái ${memberName(id)} → ${status}`,payload:{reason,documents:docs},status:'pending',requestedBy:currentUser()?.id,createdAt:iso()});save();closeModal();toast('Đã gửi yêu cầu phê duyệt');return}applyMemberStatus(id,status,reason,docs)};
window.applyMemberStatus=(id,status,reason='',docs=[])=>applyMemberStatus(id,status,reason,docs);
function applyMemberStatus(id,status,reason='',docs=[]){let m=S.members.find(x=>x.id===id);if(!m)return;m.status=status;if(status==='active'){m.stopDate='';m.stopReason='';let u=S.users.find(x=>x.memberId===id);if(u)u.active=true}else{m.stopDate=new Date().toISOString().slice(0,10);m.stopReason=reason||m.stopReason||'Theo quyết định';m.documents=[...(m.documents||[]),...(docs||[])];let u=S.users.find(x=>x.memberId===id);if(u)u.active=false}save();log('Đổi trạng thái hội viên','Member',`${m.fullName} → ${status}`);renderMembers();closeModal();toast('Đã cập nhật trạng thái','success')}
window.toggleMemberAccount=id=>{if(!['admin','president'].includes(currentUser()?.role))return toast('Chỉ Admin/Chủ tịch được khóa hoặc mở tài khoản');let u=S.users.find(x=>x.memberId===id);if(!u)return toast('Hội viên chưa có tài khoản');u.active=!u.active;save();log(u.active?'Mở tài khoản':'Khóa tài khoản','User',u.username);closeModal();toast(`Tài khoản đã ${u.active?'mở':'khóa'}`,'success')};
window.resetMemberPassword=id=>{if(!['admin','president'].includes(currentUser()?.role))return toast('Chỉ Admin/Chủ tịch được reset mật khẩu');let m=S.members.find(x=>x.id===id),u=S.users.find(x=>x.memberId===id);if(!u)return toast('Hội viên chưa có tài khoản');let p=generatePassword();u.password=p;u.forcePasswordChange=true;u.active=true;queueMail(u.email,'Mật khẩu mới VBNA Chapter 11',`Tài khoản: ${u.username}\nMật khẩu tạm: ${p}\nĐăng nhập tại https://${S.config.domain}/login`);save();log('Reset mật khẩu','User',u.username);openModal('Đã reset mật khẩu',`<div class="notice success">Email mô phỏng đã xếp hàng gửi tới ${esc(u.email)}.</div><div class="detail-item" style="margin-top:12px"><small>Mật khẩu tạm trong prototype</small><strong>${esc(p)}</strong></div>`)};
function activateMemberAccount(id){let m=S.members.find(x=>x.id===id);if(!m)return;let u=S.users.find(x=>x.memberId===id);if(!u){let p=generatePassword();u={id:uid('U'),username:m.phone,phone:m.phone,email:m.email,password:p,role:'member',memberId:m.id,active:true,forcePasswordChange:true};S.users.push(u);queueMail(m.email,'Chào mừng hội viên VBNA Chapter 11',`Xin chào ${m.fullName},\n\nChúc mừng anh/chị đã chính thức được phê duyệt trở thành hội viên VBNA Chapter 11. Với lĩnh vực ${m.industry||'kinh doanh'} tại ${m.company||'doanh nghiệp của anh/chị'}, Chapter 11 kỳ vọng anh/chị sẽ có thêm nhiều kết nối giá trị, cơ hội hợp tác và đóng góp tích cực cho cộng đồng doanh nhân.\n\nLink đăng nhập: https://${S.config.domain}/login\nTài khoản: ${m.phone}\nMật khẩu tạm: ${p}\nVui lòng đổi mật khẩu ngay lần đăng nhập đầu tiên.`)}else u.active=true;m.status='active';if(!m.admitDate)m.admitDate=new Date().toISOString().slice(0,10);save()}
function renderGuests(){q('#guestsTable').innerHTML=S.guests.map(g=>`<tr><td><b>${esc(g.fullName)}</b><br><small>${esc(g.phone)} • ${esc(g.email)}</small></td><td>${esc(g.company||'—')}<br><small>${esc(g.industry||'—')}</small></td><td>${memberName(g.inviterId)}</td><td>${statusChip(g.status)}</td><td><select onchange="updateGuestStatus('${g.id}',this.value)">${['new','contacted','attended','interested','application','approved'].map(s=>`<option ${g.status===s?'selected':''} value="${s}">${s}</option>`).join('')}</select></td></tr>`).join('')}
window.updateGuestStatus=(id,status)=>{let g=S.guests.find(x=>x.id===id);g.status=status;save();log('Cập nhật CRM','Guest',`${g.fullName} → ${status}`);renderGuests()};
function renderVbnaPeople(){q('#externalPeopleTable').innerHTML=S.vbnaPeople.map(p=>`<tr><td>${esc(p.group)}</td><td><b>${esc(p.fullName)}</b><br><small>${esc(p.phone)} • ${esc(p.email)}</small></td><td>${esc(p.chapter)}</td><td>${esc(p.department||'—')}</td><td>${esc(p.company)}</td></tr>`).join('')}
window.addExternalPerson=()=>openModal('Thêm danh mục VBNA',`<form onsubmit="saveExternalPerson(event)"><div class="form-grid"><div class="field"><label>Nhóm</label><select id="epGroup"><option>HĐSL</option><option>HĐTV</option><option>Chủ tịch Chapter</option><option>LT Chapter</option></select></div><div class="field"><label>Họ tên</label><input id="epName" required></div><div class="field"><label>SĐT</label><input id="epPhone" required></div><div class="field"><label>Email</label><input id="epEmail" type="email"></div><div class="field"><label>Chapter</label><input id="epChapter" placeholder="01–23 hoặc VBNA"></div><div class="field"><label>Ban (nếu là LT)</label><select id="epDep"><option value="">—</option>${S.departments.map(d=>`<option>${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>Doanh nghiệp</label><input id="epCompany"></div><div class="field"><label>Ngành nghề</label><input id="epIndustry"></div></div><button class="btn btn-wine" style="margin-top:14px">Lưu</button></form>`)
window.saveExternalPerson=e=>{e.preventDefault();S.vbnaPeople.push({id:uid('P'),group:q('#epGroup').value,fullName:normalizeName(q('#epName').value),phone:q('#epPhone').value,email:q('#epEmail').value,chapter:q('#epChapter').value,department:q('#epDep').value,company:q('#epCompany').value,industry:q('#epIndustry').value});save();closeModal();renderVbnaPeople();toast('Đã thêm danh mục VBNA','success')};
function renderMeetings(){q('#meetingsTable').innerHTML=S.meetings.map(m=>`<tr><td><b>${esc(m.name)}</b><br><small>${esc(m.publicCode)}</small></td><td>${fmtDate(m.date)} • ${esc(m.time)}</td><td>${esc(m.location)}</td><td>${statusChip(m.status)}</td><td>${S.attendance.filter(a=>a.meetingId===m.id).length}</td></tr>`).join('');let m=activeMeeting();q('#attendanceTable').innerHTML=S.attendance.filter(a=>a.meetingId===m.id).map(a=>`<tr><td>${esc(a.fullName)}</td><td>${esc(a.role)}</td><td>${esc(a.chapter)}</td><td>${maskPhone(a.phone)}</td><td>${memberName(a.inviterId)}</td><td>${fmtDT(a.checkedAt)}</td></tr>`).join('')}
window.addMeeting=()=>openModal('Tạo cuộc họp',`<form onsubmit="saveMeeting(event)"><div class="form-grid"><div class="field"><label>Tên cuộc họp</label><input id="mtName" required></div><div class="field"><label>Ngày</label><input id="mtDate" type="date" required></div><div class="field"><label>Giờ</label><input id="mtTime" type="time" value="07:00"></div><div class="field"><label>Địa điểm</label><input id="mtLocation" value="Hải Phòng"></div><div class="field"><label>Tuần nhiệm kỳ</label><input id="mtWeek" type="number" min="0"></div><div class="field"><label>Trạng thái</label><select id="mtStatus"><option value="scheduled">Đã lên lịch</option><option value="open">Đang mở</option></select></div></div><button class="btn btn-wine" style="margin-top:14px">Tạo cuộc họp</button></form>`)
window.saveMeeting=e=>{e.preventDefault();let status=q('#mtStatus').value;if(status==='open')S.meetings.forEach(x=>x.status=x.status==='open'?'closed':x.status);let m={id:uid('M'),name:q('#mtName').value,date:q('#mtDate').value,time:q('#mtTime').value,location:q('#mtLocation').value,termWeek:Number(q('#mtWeek').value||0),status,publicCode:uid('C11').slice(0,12)};S.meetings.push(m);save();closeModal();renderMeetings();toast('Đã tạo cuộc họp','success')};
function rankPeople(mode='giver'){let map={};for(let o of S.opportunities){let id,name;if(mode==='giver'){id=o.giverId;name=memberName(id)}else{id=o.receiverId;name=o.receiverName}if(!map[id])map[id]={id,name,count:0,value:0,success:0};map[id].count++;map[id].value+=o.value;if(o.status==='success')map[id].success++}return Object.values(map).sort((a,b)=>b.count-a.count||b.value-a.value)}
function renderOpportunityDashboard(){
 let ops=S.opportunities, total=ops.reduce((a,b)=>a+b.value,0),success=ops.filter(o=>o.status==='success'),m=activeMeeting();
 q('#oppTotalCount').textContent=ops.length;q('#oppTotalValue').textContent=money(total);
 q('#opportunitiesTable').innerHTML=ops.slice().reverse().map(o=>`<tr><td>${fmtDT(o.createdAt)}</td><td>${esc(memberName(o.giverId))}</td><td>${esc(o.receiverName)}<br><small>${o.receiverType==='member'?'Hội viên':'Khách mời'}</small></td><td>${esc(o.type)}</td><td class="text-money">${money(o.value)}</td><td>${statusChip(o.status)}</td></tr>`).join('');
 let section=q('#section-opportunities'); let old=q('#oppAdvanced'); if(old)old.remove();
 let today=new Date().toISOString().slice(0,10), month=today.slice(0,7), year=today.slice(0,4), mon=Number(today.slice(5,7)), qStart=Math.floor((mon-1)/3)*3+1;
 let byDate=(pred)=>ops.filter(o=>pred(new Date(o.createdAt)));
 let dToday=byDate(d=>d.toISOString().slice(0,10)===today), dMonth=byDate(d=>d.toISOString().slice(0,7)===month), dQuarter=byDate(d=>d.getFullYear()==year&&d.getMonth()+1>=qStart&&d.getMonth()+1<qStart+3), dYear=byDate(d=>String(d.getFullYear())===year), dMeeting=ops.filter(o=>o.meetingId===m.id);
 let div=document.createElement('div');div.id='oppAdvanced';div.innerHTML=`<div class="kpi-grid" style="margin-top:18px"><div class="kpi"><span>Cơ hội thành công</span><strong>${success.length}</strong><small>${money(success.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Buổi họp hiện tại</span><strong>${dMeeting.length}</strong><small>${money(dMeeting.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Tháng hiện tại</span><strong>${dMonth.length}</strong><small>${money(dMonth.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Năm hiện tại</span><strong>${dYear.length}</strong><small>${money(dYear.reduce((a,b)=>a+b.value,0))}</small></div></div><div class="dashboard-grid"><section class="panel"><h3>Vinh danh người trao cơ hội</h3>${rankPeople('giver').slice(0,10).map((r,i)=>`<div class="metric-row"><span>${i+1}. ${esc(r.name)}</span><b>${r.count} phiếu • ${money(r.value)}</b></div>`).join('')}</section><section class="panel"><h3>Vinh danh người nhận cơ hội</h3>${rankPeople('receiver').slice(0,10).map((r,i)=>`<div class="metric-row"><span>${i+1}. ${esc(r.name)}</span><b>${r.count} phiếu • ${money(r.value)}</b></div>`).join('')}</section></div><section class="panel"><h3>Báo cáo lũy kế theo kỳ</h3><div class="table-wrap"><table class="table"><thead><tr><th>Kỳ</th><th>Số phiếu</th><th>Giá trị</th></tr></thead><tbody><tr><td>Hôm nay</td><td>${dToday.length}</td><td>${money(dToday.reduce((a,b)=>a+b.value,0))}</td></tr><tr><td>Tháng hiện tại</td><td>${dMonth.length}</td><td>${money(dMonth.reduce((a,b)=>a+b.value,0))}</td></tr><tr><td>Quý hiện tại</td><td>${dQuarter.length}</td><td>${money(dQuarter.reduce((a,b)=>a+b.value,0))}</td></tr><tr><td>Năm hiện tại</td><td>${dYear.length}</td><td>${money(dYear.reduce((a,b)=>a+b.value,0))}</td></tr><tr><td>Toàn dữ liệu</td><td>${ops.length}</td><td>${money(total)}</td></tr></tbody></table></div></section>`;section.append(div)
}
function renderFinance(){let inc=S.finance.filter(f=>f.kind==='income'&&f.status==='approved').reduce((a,b)=>a+b.amount,0),exp=S.finance.filter(f=>f.kind==='expense'&&f.status==='approved').reduce((a,b)=>a+b.amount,0),pending=S.finance.filter(f=>f.status==='pending').reduce((a,b)=>a+b.amount,0);q('#finIncome').textContent=money(inc);q('#finExpense').textContent=money(exp);q('#finBalance').textContent=money(inc-exp);q('#finPending').textContent=money(pending);q('#financeTable').innerHTML=S.finance.slice().reverse().map(f=>`<tr><td><b>${esc(f.id)}</b><br><small>${fmtDate(f.date)}</small></td><td>${f.kind==='income'?'Thu':'Chi'} • ${esc(f.costType==='fixed'?'Cố định':'Linh hoạt')}</td><td>${esc(f.category)}<br><small>${esc(f.description)}</small></td><td class="text-money">${money(f.amount)}</td><td>${statusChip(f.status)}</td><td>${(f.files||[]).length} file</td><td>${f.status==='pending'&&['admin','president'].includes(currentUser()?.role)?`<button class="btn btn-soft btn-sm" onclick="approveFinance('${f.id}')">Duyệt</button>`:''}</td></tr>`).join('')}
window.approveFinance=id=>{let f=S.finance.find(x=>x.id===id);f.status='approved';save();log('Duyệt tài chính','Finance',id);renderFinance();toast('Đã duyệt giao dịch','success')};
function renderFees(){let month=new Date().toISOString().slice(0,7);q('#feesTable').innerHTML=S.members.filter(m=>m.status==='active').map(m=>{let mon=S.feePayments.find(f=>f.memberId===m.id&&f.feeType==='monthly'&&f.period===month&&f.status==='confirmed');let yr=S.feePayments.find(f=>f.memberId===m.id&&f.feeType==='annual'&&f.period===m.annualDueDate?.slice(0,4)&&f.status==='confirmed');return `<tr><td><b>${esc(m.fullName)}</b><br><small>${esc(m.phone)}</small></td><td>${mon?statusChip('confirmed'):`<span class="chip red">Chưa nộp ${money(S.config.fees.monthly)}</span>`}</td><td>${yr?statusChip('confirmed'):`<span class="chip gold">Hạn ${fmtDate(m.annualDueDate)}</span>`}</td><td><button class="btn btn-soft btn-sm" onclick="confirmFee('${m.id}','monthly')">Xác nhận phí quỹ</button> <button class="btn btn-outline btn-sm" onclick="confirmFee('${m.id}','annual')">Xác nhận thường niên</button></td></tr>`}).join('')}
window.confirmFee=(id,type)=>{if(!['admin','president','secretary_lead'].includes(currentUser()?.role))return toast('Bạn không có quyền xác nhận phí');let m=S.members.find(x=>x.id===id),period=type==='monthly'?new Date().toISOString().slice(0,7):m.annualDueDate.slice(0,4),amount=type==='monthly'?S.config.fees.monthly:S.config.fees.annual;if(S.feePayments.some(f=>f.memberId===id&&f.feeType===type&&f.period===period&&f.status==='confirmed'))return toast('Khoản phí này đã được xác nhận');let fid=`PT-${new Date().getFullYear()}-${String(S.finance.length+1).padStart(4,'0')}`;S.feePayments.push({id:uid('FP'),memberId:id,feeType:type,period,amount,status:'confirmed',confirmedAt:iso(),financeId:fid});S.finance.push({id:fid,kind:'income',category:type==='monthly'?'Phí sinh hoạt':'Phí thường niên',costType:'fixed',amount,memberId:id,date:new Date().toISOString().slice(0,10),description:`${type==='monthly'?'Phí quỹ':'Phí thường niên'} ${period}`,status:'approved',files:[],createdBy:currentUser()?.id});save();log('Xác nhận phí','Fee',`${m.fullName} • ${type} • ${period}`);renderFees();toast('Đã xác nhận và tự tạo phiếu thu','success')};
function renderDocuments(){let rows=[];for(let m of S.members)for(let d of m.documents||[])rows.push({owner:m.fullName,kind:d.typeGroup||'Hồ sơ',name:d.name,date:m.admitDate,key:d.storageKey});for(let f of S.finance)for(let x of f.files||[])rows.push({owner:f.id,kind:'Chứng từ tài chính',name:typeof x==='string'?x:x.name,date:f.date,key:typeof x==='object'?x.storageKey:null});q('#documentsTable').innerHTML=rows.map(r=>`<tr><td>${esc(r.owner)}</td><td>${esc(r.kind)}</td><td>${esc(r.name)}</td><td>${fmtDate(r.date)}${r.key?`<br><button class="btn btn-soft btn-sm" onclick="downloadStoredFile('${r.key}')">Tải file</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Chưa có file</td></tr>'}
function renderLeadership(){q('#leadershipGrid').innerHTML=S.departments.map(d=>{let ms=S.members.filter(m=>m.departmentIds?.includes(d.id)&&m.status==='active');return `<article class="card"><div class="eyebrow">${esc(d.name)}</div><h3>${esc(ms[0]?.fullName||'Chưa phân công')}</h3><p>${esc(d.scope)}</p><div>${ms.slice(1).map(m=>`<span class="chip gray">${esc(m.fullName)}</span>`).join('')}</div><a class="btn btn-soft btn-sm" style="margin-top:12px" href="departments.html?dep=${d.id}">Mở Dashboard Ban</a></article>`}).join('')}
function renderPowerTeamsAdmin(){q('#powerTeamGrid').innerHTML=S.powerTeams.map(p=>`<article class="card power-card"><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div>${S.members.filter(m=>m.powerTeamId===p.id&&m.status==='active').map(m=>`<span class="chip red">${esc(m.fullName)}</span>`).join('')}</div></article>`).join('')}
function renderReports(){let periods=[{name:'Nhiệm kỳ',from:S.config.term.start,to:S.config.term.end},{name:'Tháng hiện tại',from:new Date().toISOString().slice(0,7)+'-01',to:new Date().toISOString().slice(0,10)}];let ops=S.opportunities,fin=S.finance.filter(f=>f.status==='approved');q('#reportSummary').innerHTML=`<div class="kpi-grid"><div class="kpi"><span>Tổng hội viên</span><strong>${S.members.filter(m=>m.status==='active').length}</strong><small>Hiện tại</small></div><div class="kpi"><span>Tổng khách mời</span><strong>${S.guests.length}</strong><small>CRM</small></div><div class="kpi"><span>Cơ hội thành công</span><strong>${ops.filter(o=>o.status==='success').length}</strong><small>${money(ops.filter(o=>o.status==='success').reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Số dư quỹ</span><strong>${money(fin.reduce((a,b)=>a+(b.kind==='income'?b.amount:-b.amount),0))}</strong><small>Đã duyệt</small></div></div><div class="panel"><h3>Chu kỳ báo cáo</h3>${periods.map(p=>`<div class="metric-row"><span>${p.name}</span><b>${fmtDate(p.from)} → ${fmtDate(p.to)}</b></div>`).join('')}</div>`}
function renderApprovals(){q('#approvalTable').innerHTML=S.approvals.map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.type)}</td><td>${userName(a.requestedBy)}</td><td>${fmtDT(a.createdAt)}</td><td>${statusChip(a.status)}</td><td>${a.status==='pending'&&['admin','president'].includes(currentUser()?.role)?`<button class="btn btn-soft btn-sm" onclick="approveRequest('${a.id}')">Phê duyệt</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Không có yêu cầu</td></tr>';q('#auditTable').innerHTML=S.audit.slice(0,80).map(a=>`<tr><td>${fmtDT(a.time)}</td><td>${esc(userName(a.userId))}</td><td>${esc(a.action)}</td><td>${esc(a.entity)}</td><td>${esc(a.detail)}</td></tr>`).join('')}
window.approveRequest=id=>{let a=S.approvals.find(x=>x.id===id);if(!a)return;if(a.type==='member_admission')activateMemberAccount(a.entityId);if(a.type==='member_status')applyMemberStatus(a.entityId,a.targetStatus,a.payload?.reason||'',a.payload?.documents||[]);a.status='approved';a.approvedBy=currentUser().id;a.approvedAt=iso();save();log('Phê duyệt','Approval',a.title);renderApprovals();toast('Đã phê duyệt','success')};
function renderSettings(){q('#settingsInfo').innerHTML=`<div class="detail-list"><div class="detail-item"><small>Tên miền</small><strong>${esc(S.config.domain)}</strong></div><div class="detail-item"><small>Nhiệm kỳ</small><strong>${fmtDate(S.config.term.start)} – ${fmtDate(S.config.term.end)}</strong></div><div class="detail-item"><small>Phí thường niên</small><strong>${money(S.config.fees.annual)}</strong></div><div class="detail-item"><small>Phí quỹ tháng</small><strong>${money(S.config.fees.monthly)}</strong></div><div class="detail-item"><small>Email chờ gửi</small><strong>${S.mailOutbox.length}</strong></div><div class="detail-item"><small>Phiên bản dữ liệu</small><strong>ERP V${S.version}</strong></div></div><div class="toolbar" style="margin-top:16px">${isAdmin()?'<button class="btn btn-outline" onclick="resetDemo()">Khôi phục dữ liệu demo</button>':''}<button class="btn btn-dark" onclick="logout()">Đăng xuất</button></div>`}
window.resetDemo=()=>{if(!isAdmin())return toast('Chỉ Admin cao nhất được thao tác');if(!confirm('Khôi phục toàn bộ dữ liệu demo?'))return;S=seed();save();toast('Đã khôi phục dữ liệu demo','success');setTimeout(()=>location.reload(),600)};
function financeAccess(){return ['admin','president','secretary_lead'].includes(currentUser()?.role)}
function renderStandaloneFinance(){if(!requireAuth())return;if(!financeAccess()){location.href='departments.html?dep=secretariat';return}let el=q('#standaloneFinanceTable');if(el)el.innerHTML=S.finance.slice().reverse().map(f=>`<tr><td>${esc(f.id)}</td><td>${f.kind==='income'?'Thu':'Chi'}</td><td>${esc(f.category)}</td><td>${money(f.amount)}</td><td>${statusChip(f.status)}</td></tr>`).join('')}
window.submitFinance=async e=>{e.preventDefault();if(!requireAuth())return;if(!financeAccess())return toast('Bạn không có quyền nhập tài chính');let kind=q('#finKind').value,amount=Number(q('#finAmount').value||0),files=await persistInputFiles(q('#finFiles'),10,'finance');let rec={id:`${kind==='income'?'PT':'PC'}-${new Date().getFullYear()}-${String(S.finance.length+1).padStart(4,'0')}`,kind,category:q('#finCategory').value,costType:q('#finCostType').value,amount,memberId:q('#finMember')?.value||null,date:q('#finDate').value,description:q('#finDescription').value,method:q('#finMethod')?.value||'',files,status:['admin','president'].includes(currentUser()?.role)?'approved':'pending',createdBy:currentUser().id};S.finance.push(rec);save();log('Tạo phiếu tài chính','Finance',rec.id);q('#financeSuccess')?.classList.remove('hide');e.target.reset();initFinanceEntry();toast('Đã lưu phiếu thu/chi','success')};
function initFinanceEntry(){if(!requireAuth())return;if(!financeAccess()){location.href='departments.html?dep=secretariat';return}let sel=q('#finMember');if(sel)sel.innerHTML='<option value="">Không áp dụng</option>'+S.members.filter(m=>m.status==='active').map(m=>`<option value="${m.id}">${esc(m.fullName)}</option>`).join('');let d=q('#finDate');if(d&&!d.value)d.value=new Date().toISOString().slice(0,10)}
function renderDepartments(){if(!requireAuth())return;let params=new URLSearchParams(location.search),depId=params.get('dep')||'president',dep=S.departments.find(d=>d.id===depId)||S.departments[0],u=currentUser(),manage=canManageDepartment(dep.id,u);let menu=q('#departmentMenu');if(menu)menu.innerHTML=S.departments.map(d=>`<a class="side-link ${d.id===dep.id?'active':''}" href="departments.html?dep=${d.id}"><span class="side-icon">◈</span><span>${esc(d.name)}</span></a>`).join('');q('#departmentName')&&(q('#departmentName').textContent=dep.name);q('#departmentScope')&&(q('#departmentScope').textContent=dep.scope);let members=S.members.filter(m=>m.departmentIds?.includes(dep.id)&&m.status==='active'),m=activeMeeting(),at=S.attendance.filter(a=>a.meetingId===m.id),ops=S.opportunities,content=`<div class="kpi-grid"><div class="kpi"><span>Thành viên Ban</span><strong>${members.length}</strong><small>${manage?'Có quyền quản trị':'Chế độ xem'}</small></div><div class="kpi"><span>Điểm danh buổi hiện tại</span><strong>${at.length}</strong><small>${esc(m.name)}</small></div><div class="kpi"><span>Cơ hội nhiệm kỳ</span><strong>${ops.length}</strong><small>${money(ops.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Việc cần xử lý</span><strong>${S.approvals.filter(a=>a.status==='pending').length}</strong><small>Yêu cầu chờ duyệt</small></div></div><div class="dashboard-grid"><section class="panel"><h3>Nhân sự ${esc(dep.name)}</h3>${members.map(x=>`<div class="metric-row"><span>${esc(x.fullName)}</span><b>${esc(x.company)}</b></div>`).join('')||'<div class="empty">Chưa phân công nhân sự</div>'}</section><section class="panel"><h3>Quyền truy cập</h3><div class="notice ${manage?'success':'warn'}">${manage?'Bạn có quyền xem dữ liệu chi tiết và thao tác của Ban này.':'Bạn là hội viên Chapter 11 nên được xem Dashboard công khai; dữ liệu chi tiết chỉ hiện cho Trưởng ban, thành viên được phân quyền, Chủ tịch và Admin.'}</div></section></div>`;
 if(dep.id==='secretariat')content+=`<section class="panel"><div class="toolbar"><h3>Tài chính – Thu chi – Sổ quỹ</h3><a class="btn btn-wine btn-sm" href="finance.html">Mở tài chính</a></div><div class="metric-list">${S.finance.slice(-6).reverse().map(f=>`<div class="metric-row"><span>${esc(f.id)} • ${esc(f.description)}</span><b>${money(f.amount)}</b></div>`).join('')}</div></section>`;
 if(dep.id==='development')content+=`<section class="panel"><h3>Power Team</h3><div class="grid-3">${S.powerTeams.map(p=>`<article class="card"><b>${esc(p.name)}</b><p>${S.members.filter(x=>x.powerTeamId===p.id&&x.status==='active').length} hội viên</p></article>`).join('')}</div></section>`;
 if(dep.id==='events')content+=`<section class="panel"><h3>Sự kiện trọng điểm</h3>${S.events.filter(e=>e.departmentId==='events').map(e=>`<div class="notice warn"><b>${esc(e.title)}</b><br>${fmtDate(e.date)} • ${esc(e.description)}</div>`).join('')}</section>`;
 if(dep.id==='guests')content+=`<section class="panel"><h3>CRM khách mời</h3>${S.guests.map(g=>`<div class="metric-row"><span>${esc(g.fullName)} • ${esc(g.industry)}</span><b>${esc(g.status)}</b></div>`).join('')}</section>`;
 q('#departmentDashboard')&&(q('#departmentDashboard').innerHTML=content)}
function renderSupport(){if(!requireAuth())return;let el=q('#supportTickets');if(el)el.innerHTML=S.supportTickets.filter(t=>isAdmin()||t.createdBy===currentUser().id).map(t=>`<div class="card"><div class="toolbar"><b>${esc(t.subject)}</b>${statusChip(t.status)}</div><p>${esc(t.message)}</p><small>${fmtDT(t.createdAt)}</small></div>`).join('')||'<div class="empty">Chưa có yêu cầu hỗ trợ</div>'}
window.submitSupport=e=>{e.preventDefault();S.supportTickets.unshift({id:uid('SUP'),subject:q('#supportSubject').value,message:q('#supportMessage').value,priority:q('#supportPriority').value,status:'open',createdBy:currentUser().id,createdAt:iso()});save();log('Tạo yêu cầu hỗ trợ','Support',q('#supportSubject').value);e.target.reset();renderSupport();toast('Đã gửi yêu cầu hỗ trợ','success')};
function renderMemberPortal(){if(!requireAuth())return;let u=currentUser(),m=currentMember();if(!m){q('#memberPortal')&&(q('#memberPortal').innerHTML='<div class="notice warn">Tài khoản này chưa liên kết hồ sơ hội viên.</div>');return}let att=S.attendance.filter(a=>a.personId===m.id),given=S.opportunities.filter(o=>o.giverId===m.id),received=S.opportunities.filter(o=>o.receiverId===m.id),month=new Date().toISOString().slice(0,7),monthly=S.feePayments.some(f=>f.memberId===m.id&&f.feeType==='monthly'&&f.period===month&&f.status==='confirmed');let annual=S.feePayments.some(f=>f.memberId===m.id&&f.feeType==='annual'&&f.period===m.annualDueDate?.slice(0,4)&&f.status==='confirmed');q('#portalMemberName')&&(q('#portalMemberName').textContent=m.fullName);q('#memberPortal')&&(q('#memberPortal').innerHTML=`<div class="kpi-grid"><div class="kpi"><span>Điểm danh</span><strong>${att.length}</strong><small>Lịch sử trong dữ liệu</small></div><div class="kpi"><span>Đã trao cơ hội</span><strong>${given.length}</strong><small>${money(given.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Được nhận cơ hội</span><strong>${received.length}</strong><small>${money(received.reduce((a,b)=>a+b.value,0))}</small></div><div class="kpi"><span>Power Team</span><strong style="font-size:18px">${esc(powerName(m.powerTeamId))}</strong><small>${esc(m.industry)}</small></div></div><div class="dashboard-grid"><section class="panel"><h3>Hồ sơ của tôi</h3><div class="detail-list"><div class="detail-item"><small>Họ tên</small><strong>${esc(m.fullName)}</strong></div><div class="detail-item"><small>SĐT / Email</small><strong>${esc(m.phone)} • ${esc(m.email)}</strong></div><div class="detail-item"><small>Doanh nghiệp</small><strong>${esc(m.company)}</strong></div><div class="detail-item"><small>Ngành nghề</small><strong>${esc(m.industry)}</strong></div><div class="detail-item"><small>Ngày kết nạp</small><strong>${fmtDate(m.admitDate)}</strong></div><div class="detail-item"><small>Hạn thường niên</small><strong>${fmtDate(m.annualDueDate)}</strong></div></div></section><section class="panel"><h3>Trạng thái phí</h3><div class="metric-row"><span>Phí quỹ tháng ${month}</span><b>${monthly?'Đã xác nhận':'Chưa xác nhận'}</b></div><div class="metric-row"><span>Phí thường niên ${money(S.config.fees.annual)}</span><b>${annual?'Đã xác nhận':'Hạn '+fmtDate(m.annualDueDate)}</b></div><div class="notice ${monthly?'success':'warn'}" style="margin-top:12px">Khi Ban Thư ký xác nhận đã nộp, cảnh báo phí tương ứng sẽ tự tắt.</div></section></div><section class="panel"><div class="toolbar"><h3>Dashboard các Ban</h3><a class="btn btn-outline btn-sm" href="departments.html">Xem toàn bộ</a></div><div class="grid-3">${S.departments.map(d=>`<a class="card" href="departments.html?dep=${d.id}"><div class="eyebrow">${esc(d.name)}</div><b>${esc(d.scope)}</b></a>`).join('')}</div></section>`);showAlerts()}
/* Lucky Draw */
let luckyTimer=null,luckyAudioCtx=null,luckyMusic=false,luckyBeat=null;
function eligibleLucky(){let m=activeMeeting(),seen=new Set(),removed=new Set(S.lucky.removedIds||[]),winners=new Set((S.lucky.winners||[]).filter(w=>w.meetingId===m.id).map(w=>w.personKey));return S.attendance.filter(a=>a.meetingId===m.id).filter(a=>{let key=a.personId||a.phone;if(!key||seen.has(key)||removed.has(key)||winners.has(key))return false;seen.add(key);return true}).map(a=>({...a,personKey:a.personId||a.phone}))}
function renderLucky(){if(!requireAuth())return;let list=eligibleLucky();q('#drawPeopleCount')&&(q('#drawPeopleCount').textContent=list.length);q('#drawPeople')&&(q('#drawPeople').innerHTML=list.map(p=>`<div class="person-row"><strong>${esc(p.fullName)}</strong><small>${esc(p.role)} • ${esc(p.chapter)} • ${maskPhone(p.phone)}</small></div>`).join('')||'<div class="empty" style="color:#fff">Không còn người hợp lệ</div>');let wins=(S.lucky.winners||[]).filter(w=>w.meetingId===activeMeeting().id);q('#winnerList')&&(q('#winnerList').innerHTML=wins.map((w,i)=>`<div class="winner-row"><div class="row"><div><strong>${i+1}. ${esc(w.fullName)}</strong><small>${esc(w.role)} • ${esc(w.chapter)} • ${maskPhone(w.phone)} • ${esc(w.company||'')}</small></div><button class="btn btn-outline btn-sm" onclick="removeLuckyWinner('${w.personKey}')">Loại khỏi phiên</button></div></div>`).join('')||'<div class="empty" style="color:#fff">Chưa có người trúng</div>');qa('.mode-card').forEach(c=>c.onclick=()=>{qa('.mode-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');q('#drawMode').value=c.dataset.mode;q('#winnerCount').disabled=c.dataset.mode==='single';if(c.dataset.mode==='single')q('#winnerCount').value=1});bindLuckyFiles();setTimeout(startDefaultLuckyMusic,300)}
function bindLuckyFiles(){let bg=q('#bgFile'),v=q('#vbnaLogo'),c=q('#c11Logo');if(bg&&!bg.dataset.bound){bg.dataset.bound=1;bg.onchange=e=>previewFileBg(e.target.files[0])}if(v&&!v.dataset.bound){v.dataset.bound=1;v.onchange=e=>previewImg(e.target.files[0],'#vbnaLogoPreview')}if(c&&!c.dataset.bound){c.dataset.bound=1;c.onchange=e=>previewImg(e.target.files[0],'#c11LogoPreview')}}
function previewFileBg(f){if(!f)return;let r=new FileReader();r.onload=()=>{q('.lucky').style.backgroundImage=`linear-gradient(rgba(50,0,8,.68),rgba(90,0,20,.72)),url('${r.result}')`;q('.lucky').style.backgroundSize='cover';q('.lucky').style.backgroundPosition='center'};r.readAsDataURL(f)}
function previewImg(f,sel){if(!f)return;let r=new FileReader();r.onload=()=>{let im=q(sel);im.src=r.result;im.classList.remove('hide')};r.readAsDataURL(f)}
function synthBeat(){try{if(!luckyAudioCtx)luckyAudioCtx=new (window.AudioContext||window.webkitAudioContext)();if(luckyAudioCtx.state==='suspended')luckyAudioCtx.resume().catch(()=>{});let t=luckyAudioCtx.currentTime;[0,0.18,0.36,0.54].forEach((off,i)=>{let o=luckyAudioCtx.createOscillator(),g=luckyAudioCtx.createGain();o.type=i%2?'square':'triangle';o.frequency.value=[523,659,784,659][i];g.gain.setValueAtTime(.0001,t+off);g.gain.exponentialRampToValueAtTime(.035,t+off+.01);g.gain.exponentialRampToValueAtTime(.0001,t+off+.12);o.connect(g).connect(luckyAudioCtx.destination);o.start(t+off);o.stop(t+off+.14)})}catch{}}
function startDefaultLuckyMusic(){if(luckyMusic)return;luckyMusic=true;synthBeat();luckyBeat=setInterval(synthBeat,760)}
function stopDefaultLuckyMusic(){luckyMusic=false;if(luckyBeat){clearInterval(luckyBeat);luckyBeat=null}}
window.toggleLuckyMusic=()=>{let a=q('#customLotteryAudio');if(a?.src){if(a.paused){a.play().catch(()=>toast('Trình duyệt chặn tự phát âm thanh; hãy bấm nút thêm một lần.'));stopDefaultLuckyMusic()}else a.pause();return}luckyMusic?stopDefaultLuckyMusic():startDefaultLuckyMusic()};
window.loadLuckyMusic=e=>{let f=e.target.files[0];if(!f)return;let a=q('#customLotteryAudio');a.src=URL.createObjectURL(f);a.loop=true;stopDefaultLuckyMusic();a.play().catch(()=>toast('Đã nạp nhạc. Bấm Phát/Tạm dừng nhạc để kích hoạt.'))};
window.shuffleLucky=()=>{S.lucky.shuffleSeed=(S.lucky.shuffleSeed||0)+1;save();let list=eligibleLucky().sort(()=>Math.random()-.5);q('#drawPeople').innerHTML=list.map(p=>`<div class="person-row"><strong>${esc(p.fullName)}</strong><small>${esc(p.role)} • ${maskPhone(p.phone)}</small></div>`).join('');toast('Đã xáo trộn danh sách')};
window.drawLucky=()=>{if(luckyTimer)return;let list=eligibleLucky();let exclude=(q('#excludeText').value||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);list=list.filter(p=>!exclude.some(x=>p.fullName.toLowerCase().includes(x)||p.phone.includes(x)));let count=q('#drawMode').value==='single'?1:Math.max(1,Math.min(Number(q('#winnerCount').value||1),50));if(!list.length)return toast('Không còn người đủ điều kiện quay');count=Math.min(count,list.length);let sec=Math.max(1,Number(q('#drawSeconds').value||5)),start=Date.now();startDefaultLuckyMusic();q('.slot').classList.add('celebrate');luckyTimer=setInterval(()=>{let p=list[Math.floor(Math.random()*list.length)];q('#slotName').textContent=p.fullName;q('#slotMeta').textContent=`${p.role} • ${p.chapter} • ${maskPhone(p.phone)}`;if(Date.now()-start>=sec*1000){clearInterval(luckyTimer);luckyTimer=null;let picked=[];let pool=[...list];for(let i=0;i<count;i++){let ix=Math.floor(Math.random()*pool.length);picked.push(pool.splice(ix,1)[0])}for(let p of picked)S.lucky.winners.push({id:uid('WIN'),meetingId:activeMeeting().id,personKey:p.personKey,fullName:p.fullName,phone:p.phone,role:p.role,chapter:p.chapter,company:p.company||'',wonAt:iso()});save();let main=picked[0];q('#slotName').textContent=count===1?main.fullName:`${count} NGƯỜI TRÚNG`;q('#slotMeta').textContent=count===1?`${main.role} • ${main.chapter} • ${maskPhone(main.phone)}`:picked.map(x=>x.fullName).join(' • ');renderLucky();log('Lucky Draw','Winner',picked.map(x=>x.fullName).join(', '));setTimeout(()=>q('.slot')?.classList.remove('celebrate'),1500)}},80)};
window.removeLuckyWinner=key=>{if(!S.lucky.removedIds.includes(key))S.lucky.removedIds.push(key);save();renderLucky();toast('Đã loại người này khỏi các lượt quay tiếp')};
window.resetLucky=()=>{if(!confirm('Làm mới kết quả Lucky Draw của buổi họp hiện tại?'))return;let mid=activeMeeting().id;S.lucky.winners=S.lucky.winners.filter(w=>w.meetingId!==mid);S.lucky.removedIds=[];save();renderLucky();q('#slotName').textContent='Sẵn sàng quay';q('#slotMeta').textContent='Danh sách lấy từ điểm danh, đã khử trùng'};
window.exportReportCsv=()=>{if(!requireAuth())return;let rows=[['LOAI','HO TEN','DOANH NGHIEP','NGANH NGHE','TRANG THAI'],...S.members.map(m=>['HOI VIEN',m.fullName,m.company,m.industry,m.status]),[],['CO HOI','NGUOI TRAO','NGUOI NHAN','LOAI','GIA TRI','TRANG THAI'],...S.opportunities.map(o=>['CO HOI',memberName(o.giverId),o.receiverName,o.type,o.value,o.status]),[],['TAI CHINH','MA PHIEU','DANH MUC','NOI DUNG','SO TIEN','TRANG THAI'],...S.finance.map(f=>['TAI CHINH',f.id,f.category,f.description,(f.kind==='income'?f.amount:-f.amount),f.status])];let csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`VBNA_Chapter11_Report_${new Date().toISOString().slice(0,10)}.csv`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);log('Xuất báo cáo','Report','CSV tổng hợp')};
/* init */
document.addEventListener('DOMContentLoaded',()=>{updateMeetingText();let p=document.body.dataset.page||'';if(['admin','departments','finance','finance-entry','support','lucky','member-portal'].includes(p)&&!requireAuth())return;({home:renderHome,'members-public':renderPublicMembersPage,'power-teams':renderPowerTeams,meeting:renderMeetingPage,checkin:renderCheckin,'guest-register':renderGuestRegister,opportunity:renderOpportunity,admin:renderAdmin,finance:renderStandaloneFinance,'finance-entry':initFinanceEntry,departments:renderDepartments,support:renderSupport,'member-portal':renderMemberPortal,lucky:renderLucky})[p]?.();if(currentUser()&&p!=='admin')setTimeout(showAlerts,350);if(p==='lucky')document.addEventListener('pointerdown',()=>{if(luckyAudioCtx?.state==='suspended')luckyAudioCtx.resume().catch(()=>{})},{once:true})});
})();
