/* C11 member spreadsheet import; guest/VBNA directories are not import targets. */
const canImportMembers=()=>canLead()||currentUser()?.role==='vice_president';
const isC11=m=>m.chapter===undefined||m.chapter===null||m.chapter===''||String(m.chapter)==='11';
const phoneKey=p=>String(p||'').replace(/[\s().-]/g,'').replace(/^\+84/,'0');
const memberColumns=[['id','Mã hội viên'],['chapter','Chapter'],['fullName','Họ tên'],['phone','Số điện thoại'],['email','Email'],['dob','Ngày sinh'],['gender','Giới tính'],['homeAddress','Địa chỉ nhà riêng'],['company','Tên doanh nghiệp'],['title','Chức vụ doanh nghiệp'],['taxId','Mã số thuế'],['businessAddress','Địa chỉ kinh doanh'],['website','Website'],['industry','Ngành nghề chính'],['secondaryIndustry','Ngành nghề phụ'],['products','Sản phẩm dịch vụ'],['powerTeamId','Mã Power Team'],['joinDate','Ngày gia nhập'],['admitDate','Ngày kết nạp'],['annualDueDate','Hạn phí thường niên']];
let memberImportPlan=null;
function memberImportControls(){return `<section class="panel" id="memberImportPanel"><div class="toolbar"><div><h3>Excel hội viên Chapter 11</h3><p class="small-text">Mã hội viên / số điện thoại dùng để đối chiếu. Người ngoài Chapter 11 không được nhập tại đây.</p></div><div class="section-links">${button('Tải mẫu thêm hội viên','exportMemberTemplate(false)','btn-outline')}${button('Xuất danh sách để cập nhật','exportMemberTemplate(true)','btn-outline')}</div></div><label for="memberExcel">Nhập file đã điền (.xlsx)</label><input id="memberExcel" type="file" accept=".xlsx" onchange="previewMemberImport(event)"><p class="small-text">Hồ sơ mới giữ quy trình chờ Chủ tịch/Admin duyệt cấp tài khoản. Ảnh được hội viên bổ sung trong tài khoản của mình.</p><div id="memberImportPreview"></div></section>`}
function photoLabel(m){return imageSrc(m.avatar)?'Đã có ảnh':'Cần bổ sung hình ảnh'}
function memberPhotoTask(m){m.photoStatus=imageSrc(m.avatar)?'complete':'needs_photo';const pending=S.notifications.filter(n=>n.kind==='member_photo'&&n.memberId===m.id&&!n.resolvedAt);if(m.photoStatus==='complete'){pending.forEach(n=>n.resolvedAt=iso());return}if(!pending.length)S.notifications.push({id:uid('N'),kind:'member_photo',memberId:m.id,text:'Hồ sơ Chapter 11 của anh/chị cần bổ sung hình ảnh đại diện. Vào Hồ sơ của tôi để cập nhật.',createdAt:iso()});}
window.exportMemberTemplate=async(includeExisting=false)=>{if(!canImportMembers())return toast('Chỉ Phó Chủ tịch, Chủ tịch hoặc Admin được dùng chức năng này');const rows=includeExisting?S.members.filter(isC11).map(m=>memberColumns.map(([k])=>k==='chapter'?'11':m[k]||'')):[];await exportXlsx([{name:'Hoi vien C11',headers:memberColumns.map(x=>x[1]),rows},{name:'Huong dan',headers:['Mục','Cách điền'],rows:[['Phạm vi','Chỉ hội viên Chapter 11. Cột Chapter bắt buộc ghi 11.'],['Bắt buộc','Họ tên, Số điện thoại, Email, Chapter. Không đưa khách mời hoặc người ngoài vào file.'],['Thêm mới','Để trống Mã hội viên; hệ thống tạo mã và gửi hồ sơ chờ duyệt.'],['Cập nhật','Giữ Mã hội viên khi xuất danh sách; không đối chiếu theo tên vì có thể trùng tên.'],['Điện thoại / MST','Nhập kiểu văn bản để giữ số 0 đầu. Không dùng công thức.'],['Ngày','Định dạng YYYY-MM-DD, ví dụ 2026-10-01; có thể dùng ô ngày Excel.'],['Ô trống','Ô tùy chọn để trống không xóa thông tin đang có trong hồ sơ.'],['Ảnh','Không nhập ảnh trong Excel. Hồ sơ thiếu ảnh được giao yêu cầu đúng Member ID để hội viên tự bổ sung.'],['Tài khoản','Hồ sơ mới được duyệt cấp tài khoản theo quy trình đang có. Import không thay đổi quyền hay mật khẩu.'],['Mã Power Team',S.powerTeams.map(p=>p.id+' = '+p.name).join('; ')]]}],includeExisting?'VBNA_C11_Cap_nhat_hoi_vien.xlsx':'VBNA_C11_Mau_them_hoi_vien.xlsx');};
function xmlDocument(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('Cấu trúc Excel không hợp lệ');return doc}
async function readMemberWorkbook(file){
 if(!file||!file.name.toLowerCase().endsWith('.xlsx')||file.size>8*1024*1024)throw Error('Chọn file .xlsx tối đa 8 MB');
 const zip=await JSZip.loadAsync(file);const read=async path=>{const f=zip.file(path);if(!f)throw Error('File Excel thiếu '+path);const text=await f.async('string');if(text.length>20000000)throw Error('Dữ liệu Excel vượt giới hạn');return xmlDocument(text)};
 const wb=await read('xl/workbook.xml'),sheet=[...wb.getElementsByTagName('sheet')].find(s=>s.getAttribute('name')==='Hoi vien C11');if(!sheet)throw Error('Giữ tên sheet Hoi vien C11 trong mẫu');
 const id=sheet.getAttribute('r:id'),rels=await read('xl/_rels/workbook.xml.rels'),rel=[...rels.getElementsByTagName('Relationship')].find(r=>r.getAttribute('Id')===id);if(!rel||rel.getAttribute('TargetMode')==='External')throw Error('Sheet không hợp lệ');
 const target=rel.getAttribute('Target');if(target.includes('..')||target.includes(':'))throw Error('Đường dẫn sheet không hợp lệ');const path=target.startsWith('/')?target.slice(1):'xl/'+target;
 const strings=zip.file('xl/sharedStrings.xml')?[...(await read('xl/sharedStrings.xml')).getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent).join('')):[];
 const doc=await read(path),rows=[...doc.getElementsByTagName('row')];if(rows.length>2001)throw Error('Tối đa 2.000 hội viên mỗi lần nhập');let matrix=[];
 for(const row of rows){const values=[];for(const cell of row.getElementsByTagName('c')){if(cell.getElementsByTagName('f').length)throw Error('Không dùng công thức trong sheet hội viên');let ref=cell.getAttribute('r')||'',letters=ref.match(/^[A-Z]+/)?.[0];if(!letters)throw Error('Địa chỉ ô không hợp lệ');let col=0;for(const x of letters)col=col*26+x.charCodeAt(0)-64;if(col>64)throw Error('File có quá nhiều cột');let type=cell.getAttribute('t'),v=cell.getElementsByTagName('v')[0]?.textContent||'';values[col-1]=type==='s'?strings[Number(v)]||'':type==='inlineStr'?[...cell.getElementsByTagName('t')].map(t=>t.textContent).join(''):v;}if(values.some(v=>String(v||'').trim()))matrix.push({line:Number(row.getAttribute('r')),values});}
 if(!matrix.length)throw Error('File chưa có dữ liệu');const headers=matrix.shift().values.map(v=>String(v||'').trim());if(headers.length!==memberColumns.length||memberColumns.some(([,h],i)=>headers[i]!==h))throw Error('Cột không đúng mẫu. Vui lòng dùng mẫu tải từ mục Hội viên');
 const date1904=['1','true'].includes(wb.getElementsByTagName('workbookPr')[0]?.getAttribute('date1904'));
 return {rows:matrix,date1904};
}
function memberDate(value,date1904){if(!value)return '';let s=String(value).trim();if(/^\d+(\.0+)?$/.test(s)){let n=Number(s);if(n<1||n>80000)throw Error('Ngày Excel ngoài phạm vi');s=new Date(Date.UTC(date1904?1904:1899,date1904?0:11,date1904?1:30)+n*86400000).toISOString().slice(0,10)}if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s+'T00:00:00Z'))||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)throw Error('Ngày phải có dạng YYYY-MM-DD');return s;}
function validateMemberRows(input){
 const plans=[],errors=[],seenPhones=new Set(),seenIds=new Set();
 for(const {line,values}of input.rows){try{
  const r=Object.fromEntries(memberColumns.map(([key],i)=>[key,String(values[i]??'').trim()]));
  if(r.chapter!=='11')throw Error('Chỉ chấp nhận Chapter 11');if(!r.fullName||!r.email||!r.phone)throw Error('Thiếu họ tên, số điện thoại hoặc email');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.email))throw Error('Email không hợp lệ');
  r.phone=phoneKey(r.phone);if(!/^0\d{9,10}$/.test(r.phone))throw Error('Số điện thoại phải giữ số 0 đầu (hoặc +84) và có 10–11 chữ số');
  if(seenPhones.has(r.phone)||(r.id&&seenIds.has(r.id)))throw Error('Mã hoặc số điện thoại trùng trong file');seenPhones.add(r.phone);if(r.id)seenIds.add(r.id);
  const matches=S.members.filter(m=>phoneKey(m.phone)===r.phone),byId=r.id?S.members.find(m=>m.id===r.id):null;
  if(matches.length>1)throw Error('Số điện thoại trùng trong dữ liệu hiện có');if(r.id&&!byId)throw Error('Mã hội viên không tồn tại; để trống mã khi thêm mới');
  if(byId&&matches[0]&&byId.id!==matches[0].id)throw Error('Mã hội viên và số điện thoại thuộc hai người khác nhau');
  const existing=byId||matches[0];if(existing&&!isC11(existing))throw Error('Hồ sơ hiện tại không thuộc Chapter 11');
  const account=S.users.find(u=>phoneKey(u.phone||u.username)===r.phone);if(account&&account.memberId!==existing?.id)throw Error('Điện thoại đã thuộc tài khoản khác');
  if(r.powerTeamId&&!S.powerTeams.some(p=>p.id===r.powerTeamId))throw Error('Mã Power Team không tồn tại');
  for(const key of ['dob','joinDate','admitDate','annualDueDate'])r[key]=memberDate(r[key],input.date1904);
  if(r.dob&&r.dob>localDay())throw Error('Ngày sinh không thể trong tương lai');
  const patch=Object.fromEntries(Object.entries(r).filter(([k,v])=>k!=='id'&&v!==''));patch.fullName=normalizeName(r.fullName);patch.chapter='11';
  plans.push({line,existingId:existing?.id||null,patch});
 }catch(e){errors.push('Dòng '+line+': '+e.message)}}return {plans,errors};
}
window.previewMemberImport=async e=>{memberImportPlan=null;if(!canImportMembers())return;const output=q('#memberImportPreview');output.textContent='Đang đọc file…';try{const input=await readMemberWorkbook(e.target.files[0]),result=validateMemberRows(input);if(!result.plans.length&&!result.errors.length)throw Error('Mẫu chưa có hội viên');if(result.errors.length){output.innerHTML='<div class="notice danger"><b>Chưa nhập dữ liệu. Cần sửa các lỗi sau:</b>'+result.errors.map(x=>'<p>'+esc(x)+'</p>').join('')+'</div>';return}memberImportPlan={input,snapshot:JSON.stringify({members:S.members,users:S.users,powerTeams:S.powerTeams})};output.innerHTML=`<h3>Xem trước ${result.plans.length} hồ sơ C11</h3>${table(['Dòng','Hội viên','SĐT','Xử lý','Hình ảnh'],result.plans.map(p=>[p.line,esc(p.patch.fullName),esc(p.patch.phone),p.existingId?'Cập nhật hồ sơ':'Thêm mới — chờ duyệt',p.existingId?photoLabel(S.members.find(m=>m.id===p.existingId)):'Cần bổ sung hình ảnh']))}<div class="form-actions">${button('Xác nhận nhập danh sách','commitMemberImport()')}</div>`}catch(err){output.innerHTML='<p class="notice danger">'+esc(err.message)+'</p>'}};
window.commitMemberImport=()=>{if(!canImportMembers()||!memberImportPlan)return;const plan=memberImportPlan;if(plan.snapshot!==JSON.stringify({members:S.members,users:S.users,powerTeams:S.powerTeams})){memberImportPlan=null;return toast('Dữ liệu đã thay đổi. Hãy chọn lại file để đối chiếu trước khi nhập')}
 const result=validateMemberRows(plan.input);if(result.errors.length)return toast(result.errors[0]);const before=structuredClone(S);let added=0,updated=0;
 try{for(const item of result.plans){let m=item.existingId?S.members.find(m=>m.id===item.existingId):null;if(m){Object.assign(m,item.patch);const u=S.users.find(u=>u.memberId===m.id);if(u){u.phone=m.phone;u.email=m.email;if(!['admin','chutich','thuky'].includes(u.username))u.username=m.phone}updated++;}else{m={id:uid('C11'),...item.patch,status:'pending',departmentIds:[],documents:[],avatar:'',secondaryIndustry:item.patch.secondaryIndustry||'',powerTeamId:item.patch.powerTeamId||'',joinDate:item.patch.joinDate||localDay(),admitDate:item.patch.admitDate||'',annualDueDate:item.patch.annualDueDate||'',stopDate:'',stopReason:''};S.members.push(m);S.approvals.unshift({id:uid('APR'),type:'member_admission',entityId:m.id,title:'Kết nạp '+m.fullName,status:'pending',requestedBy:currentUser().id,createdAt:iso()});added++;}memberPhotoTask(m)}
 S.audit.unshift({id:uid('AU'),time:iso(),userId:currentUser().id,action:'Nhập Excel hội viên C11',entity:'Member',detail:JSON.stringify({added,updated,changes:result.plans.map(p=>({before:p.existingId?before.members.find(m=>m.id===p.existingId):null,patch:p.patch}))})});save();memberImportPlan=null;refreshMemberImportPage();toast(`Đã thêm ${added}, cập nhật ${updated} hồ sơ C11`,'success');
 }catch(err){S=before;toast('Chưa lưu được danh sách: '+err.message)}
};
function refreshMemberImportPage(){if(document.body.dataset.page==='member-management')renderMemberManagement();else renderMembers()}
const renderMembersBeforeImport=renderMembers;
renderMembers=function(){renderMembersBeforeImport();if(!canImportMembers())return;const el=q('#section-members');q('#memberImportPanel')?.remove();el?.insertAdjacentHTML('afterbegin',memberImportControls());const rows=qa('#membersTable tr');rows.forEach(tr=>{const id=tr.querySelector('small')?.textContent?.split(' • ')[0],m=S.members.find(m=>m.id===id);if(m){if(!isC11(m)){tr.remove();return}tr.querySelector('td')?.insertAdjacentHTML('beforeend',`<br><span class="chip ${imageSrc(m.avatar)?'green':'gold'}">${photoLabel(m)}</span>`)}})};
window.renderMembers=renderMembers;
function renderMemberManagement(){if(!requireAuth())return;if(!canImportMembers()){location.href='member-portal.html';return}document.body.innerHTML=`<main class="report-page"><div class="page-tools"><div><span class="eyebrow">CHAPTER 11</span><h1>Hội viên</h1></div><a class="btn btn-outline" href="departments.html?dep=vice">Dashboard Phó Chủ tịch</a></div>${memberImportControls()}<section class="panel">${table(['Mã hội viên','Họ tên','Số điện thoại','Doanh nghiệp','Trạng thái','Hình ảnh'],S.members.filter(isC11).map(m=>[esc(m.id),esc(m.fullName),esc(m.phone),esc(m.company),statusChip(m.status),photoLabel(m)]))}</section></main>`}
const portalBeforePhoto=renderPortalV6;
renderPortalV6=function(){portalBeforePhoto();const m=currentMember();if(!m||!isC11(m))return;qa('#memberPortal p.notice').filter(el=>el.textContent.includes('Hồ sơ Chapter 11 của anh/chị cần bổ sung hình ảnh')).forEach(el=>el.remove());if(!imageSrc(m.avatar))q('#memberPortal').insertAdjacentHTML('afterbegin',`<section class="panel"><div class="toolbar"><div><h3>Bổ sung hình ảnh đại diện</h3><p>${esc(m.fullName)} · ${esc(m.id)} · Chapter 11</p></div><span class="chip gold">Cần bổ sung hình ảnh</span></div><form onsubmit="saveMyMemberPhoto(event)">${field('myMemberPhoto','Chọn ảnh đại diện','','file','accept="image/png,image/jpeg,image/webp" required')}<div class="form-actions"><button class="btn btn-wine">Cập nhật ảnh của tôi</button></div></form></section>`)};
window.saveMyMemberPhoto=async e=>{e.preventDefault();const m=currentMember();if(!m||!isC11(m))return;const id=m.id;try{const image=await readImage(q('#myMemberPhoto'));if(!image)return toast('Chọn ảnh trước khi cập nhật');if(currentMember()?.id!==id)return toast('Tài khoản đã thay đổi, vui lòng tải lại trang');m.avatar=image;memberPhotoTask(m);save();log('Hội viên tự bổ sung ảnh','Member',id);renderPortalV6();toast('Đã cập nhật ảnh đại diện','success')}catch(err){toast(err.message)}};
const bootBeforeMemberImport=bootV6;
bootV6=function(){if(document.body.dataset.page==='member-management'){if(!requireAuth())return;if(currentUser().forcePasswordChange){showForcePassword(currentUser());return}renderMemberManagement();return}bootBeforeMemberImport();if(canImportMembers()&&document.body.dataset.page==='departments'&&new URLSearchParams(location.search).get('dep')==='vice')q('#departmentDashboard').insertAdjacentHTML('afterbegin','<div class="toolbar"><a class="btn btn-wine" href="member-management.html">Hội viên C11 · Nhập / xuất Excel</a></div>')};
