function renderDepartmentsV6(){
 if(!requireAuth())return;const id=new URLSearchParams(location.search).get('dep')||'president',dep=S.departments.find(d=>d.id===id)||S.departments[0];
 q('#departmentMenu').innerHTML=S.departments.map(d=>`<a class="side-link ${d.id===dep.id?'active':''}" href="departments.html?dep=${d.id}">${esc(d.name)}</a>`).join('');q('#departmentName').textContent=dep.name;q('#departmentScope').textContent=S.config.term.name;
 q('.content-section>.notice')?.remove();let html='';const m=activeMeeting(),f=meetingFacts(m),manage=canDept(dep.id);
 if(dep.id==='secretariat'){
  if(financeAccess()){q('#departmentDashboard').innerHTML='<a class="btn btn-wine" href="finance.html">Mở sổ quỹ & công nợ</a><div id="financeBoard"></div>';renderFinanceBoard('financeBoard');return}
  html=stats([['Thành viên Ban',actives().filter(m=>m.departmentIds.includes(dep.id)).length],['Chứng từ & thu chi','Nội bộ']])+`<section class="panel"><h3>Ban Thư ký</h3><p>Liên hệ Ban Thư ký để được hỗ trợ về hồ sơ và các khoản phí của anh/chị.</p><a class="btn btn-outline" href="member-portal.html">Xem phí của tôi</a></section>`;
 }else if(dep.id==='vice'){
  html=stats([['Hội viên',f.roster.length],['Hiện diện',f.present.length],['Tỷ lệ hiện diện',Math.round(f.ratio*100)+'%'],['Doanh thu tuần trước',money(f.success)]]);
  html+=`<section class="panel"><div class="toolbar"><h3>${esc(m.name)}</h3>${manage?button('Ghi nhận nghỉ / đi thay','attendanceNoteForm()','btn-outline'):''}</div>${table(['STT','Hội viên','Bắt đầu','Check-in','Muộn / Sớm','Nghỉ ốm','Đi thay','Vắng','Ghi chú'],attendanceRows(m).map(r=>r.map(esc)))}</section>`;
  if(manage)html+=`<section class="panel"><h3>Doanh số trước khi sử dụng hệ thống</h3><div class="form-grid">${field('openingRevenue','Số tiền đầu kỳ (đ)',S.config.openingRevenue,'number','min="0"')}${field('openingRevenueDate','Từ ngày bắt đầu cộng phát sinh',S.config.openingRevenueDate,'date')}</div><div class="form-actions">${button('Lưu số dư doanh số','saveOpeningRevenue()')}</div><p class="small-text">Chỉ cộng cơ hội thành công được hội viên xác nhận từ ngày này để tránh tính trùng.</p></section>`;
 }else if(dep.id==='training')html=trainingHTML();
 else if(dep.id==='guests'){
  const ats=S.attendance,guests=ats.filter(a=>a.personType!=='member'),converted=S.guests.filter(g=>g.memberId),unique=new Set(guests.map(a=>a.personId||a.phone));
  html=stats([['Khách đã check-in',unique.size],['Lượt tham dự',guests.length],['Đã chuyển hội viên',converted.length],['Tỷ lệ chuyển đổi',unique.size?Math.round(converted.filter(g=>unique.has(g.id)||unique.has(g.phone)).length/unique.size*100)+'%':'0%']]);
  if(manage)html+=`<section class="panel"><div class="toolbar"><h3>Khách đăng ký website</h3>${button('Bổ sung check-in','manualGuestForm()','btn-outline')}</div>${table(['Khách','Ngành nghề','Người mời','Liên hệ / Trạng thái','Chuyển hội viên'],S.guests.map(g=>[`${esc(g.fullName)}<br><small>${esc(g.phone)} · ${esc(g.email)}</small>`,esc(g.industry),esc(memberName(g.inviterId)),`<select onchange="setCRM('${g.id}',this.value)">${opts([['new','Chưa liên hệ'],['unreachable','Chưa liên hệ được'],['contacted','Đã liên hệ'],['invited','Đã mời'],['attended','Đã tham dự'],['interested','Quan tâm'],['application','Làm hồ sơ'],['approved','Đã kết nạp']],g.status)}</select>`,g.memberId?esc(g.memberId):button('Tạo hồ sơ',`convertGuest('${g.id}')`,'btn-outline btn-sm')]))}</section>`;
  html+=`<section class="panel"><h3>Hội viên Chapter 11 đã tham dự</h3>${table(['Hội viên','Buổi họp','Check-in'],ats.filter(a=>a.personType==='member').map(a=>[esc(a.fullName),esc(S.meetings.find(m=>m.id===a.meetingId)?.name),fmtDT(a.checkedAt)]))}</section><section class="panel"><h3>Hội viên các Chapter đã tham dự</h3>${table(['Họ tên','Chapter','Buổi họp'],guests.filter(a=>a.chapter&&a.chapter!=='Khách').map(a=>[esc(a.fullName),esc(a.chapter),esc(S.meetings.find(m=>m.id===a.meetingId)?.name)]))}</section><section class="panel"><h3>Khách chuyển đổi vào Chapter 11</h3>${table(['Họ tên','Mã hội viên','Trạng thái hồ sơ'],converted.map(g=>[esc(g.fullName),esc(g.memberId),esc(S.members.find(m=>m.id===g.memberId)?.status)]))}</section>`;
 }else if(['events','orientation'].includes(dep.id))html=`<section class="panel"><div class="toolbar"><h3>Bản tin ${esc(dep.name)}</h3>${manage?button('Đăng thông báo',`postForm('${dep.id}')`):''}${dep.id==='events'&&manage?'<a class="btn btn-outline" href="settings.html#media">Quản lý hình ảnh & video</a>':''}</div>${postsHTML(dep.id)}</section>`;
 else if(dep.id==='development')html=stats([['Power Team',S.powerTeams.length],['Hội viên',actives().length],['Ngành nghề mở',f.openIndustries]])+`<section class="panel"><div class="toolbar"><h3>Power Team & ngành nghề</h3>${manage?'<a class="btn btn-outline" href="settings.html#teams">Chỉnh sửa danh mục</a>':''}</div><div class="grid-3">${S.powerTeams.map(p=>`<article class="card"><span class="eyebrow">${actives().filter(m=>m.powerTeamId===p.id).length} HỘI VIÊN</span><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><p>${p.openIndustries.map(esc).join(', ')||'Chưa khai báo ngành nghề mở'}</p></article>`).join('')}</div></section>`;
 else html=stats([['Hội viên',actives().length],['Buổi họp',S.meetings.length],['Cơ hội đã trao',S.opportunities.length],['Doanh thu xác nhận',money(sum(S.opportunities.filter(o=>o.confirmedAt&&o.status==='success'&&o.receiverType==='member'),'confirmedValue'))]])+`<section class="panel"><h3>Hoạt động các Ban</h3><div class="grid-3">${S.departments.map(d=>`<a class="card" href="departments.html?dep=${d.id}"><span class="eyebrow">${esc(d.name)}</span><p>${esc(d.scope)}</p><b>Xem Dashboard →</b></a>`).join('')}</div></section>`;
 if(manage)html=`<div class="toolbar"><span class="chip red">${esc(S.config.term.name)}</span><a class="btn btn-outline" href="reports.html">Lọc theo kỳ · Excel · In báo cáo</a></div>`+html;
 q('#departmentDashboard').innerHTML=html;
}
window.saveOpeningRevenue=()=>{if(!canDept('vice'))return;let n=Number(val('openingRevenue'));if(n<0||!val('openingRevenueDate'))return toast('Nhập số tiền không âm và ngày bắt đầu');let before={value:S.config.openingRevenue,date:S.config.openingRevenueDate};S.config.openingRevenue=n;S.config.openingRevenueDate=val('openingRevenueDate');auditChange('Sửa doanh số đầu kỳ','Report',before,{value:n,date:S.config.openingRevenueDate});toast('Đã lưu','success')};
window.attendanceNoteForm=()=>{if(!canDept('vice'))return;openModal('Ghi nhận tham dự',`<form onsubmit="saveAttendanceNote(event)"><div class="form-grid">${select('anMember','Hội viên',membersAt(activeMeeting().date).map(m=>[m.id,m.fullName]))}${select('anStatus','Trạng thái',[['normal','Bình thường'],['sick','Nghỉ ốm'],['substitute','Đi thay']])}${field('anSubstitute','Tên người đi thay')}${field('anEarly','Giờ về sớm','','time')}${area('anReason','Lý do / Ghi chú')}</div><div class="form-actions"><button class="btn btn-wine">Lưu ghi nhận</button></div></form>`)};
window.saveAttendanceNote=e=>{e.preventDefault();if(!canDept('vice'))return;let rec={memberId:val('anMember'),meetingId:activeMeeting().id,status:val('anStatus'),substitute:val('anSubstitute'),early:val('anEarly'),reason:val('anReason')};if(rec.status==='substitute'&&!rec.substitute)return toast('Nhập tên người đi thay');let i=S.attendanceNotes.findIndex(n=>n.memberId===rec.memberId&&n.meetingId===rec.meetingId),before=i<0?null:S.attendanceNotes[i];if(i<0)S.attendanceNotes.push(rec);else S.attendanceNotes[i]=rec;auditChange('Cập nhật điểm danh','Attendance',before,rec);closeModal();renderDepartmentsV6()};
const oldCheckin=window.submitCheckin;
window.submitCheckin=async e=>{e.preventDefault();let m=activeMeeting();if(m.status!=='open')return toast('Buổi họp chưa mở hoặc đã đóng điểm danh');let type=val('checkinType');if(type!=='chapter11'&&!requireName(val('guestName')))return;if(type==='chapter_president'&&!val('guestChapter'))return toast('Vui lòng chọn Chapter');const memberId=val('checkinMemberId');if(type==='chapter11'&&S.attendance.some(a=>a.meetingId===m.id&&a.personId===memberId))return toast('Hội viên đã điểm danh trong buổi họp này');if(type==='chapter11'&&!q('#checkinPhoto').files.length)return toast('Vui lòng chụp hoặc chọn ảnh hiện diện');let photo='';try{photo=await readImage(q('#checkinPhoto'))}catch(err){return toast(err.message)}let before=S.attendance.length;oldCheckin(e);if(S.attendance.length>before){let a=S.attendance.at(-1);a.photo=photo;a.guestCategory=type;if(type==='guest_external')a.chapter='Khách';save()}};
const oldGuestSubmit=window.submitGuest;window.submitGuest=e=>{if(!requireName(val('guestRegName'))){e.preventDefault();return}oldGuestSubmit(e)};
window.setCRM=(id,status)=>{if(!canDept('guests'))return;const g=S.guests.find(g=>g.id===id);if(status==='approved'&&!g.memberId)return toast('Cần tạo và phê duyệt hồ sơ hội viên trước');let before=g.status;g.status=status;g.contactedAt=iso();auditChange('Cập nhật CRM','Guest',before,status);renderDepartmentsV6()};
window.convertGuest=id=>{if(!canDept('guests'))return;let g=S.guests.find(g=>g.id===id);if(!g||g.memberId)return;let duplicate=S.members.find(m=>m.phone===g.phone);if(duplicate)return toast('Số điện thoại đã thuộc một hồ sơ hội viên');let industryDuplicate=actives().find(m=>m.industry.toLocaleLowerCase()===g.industry.toLocaleLowerCase());if(industryDuplicate&&!confirm('Ngành nghề trùng với '+industryDuplicate.fullName+'. Vẫn tạo hồ sơ chờ duyệt?'))return;let mem={id:uid('C11'),fullName:g.fullName,phone:g.phone,email:g.email,homeAddress:g.address,company:g.company,businessAddress:g.address,industry:g.industry,secondaryIndustry:'',products:g.products,powerTeamId:'',status:'pending',departmentIds:[],documents:[],joinDate:localDay(),admitDate:'',annualDueDate:'',avatar:'',guestId:g.id};S.members.push(mem);g.memberId=mem.id;g.status='application';requestApproval('member_admission',mem.id,'Kết nạp '+g.fullName,{guestId:g.id});log('Chuyển khách thành hồ sơ','Member',mem.id);renderDepartmentsV6();toast('Đã tạo hồ sơ chờ duyệt, giữ nguyên lịch sử khách','success')};
const oldActivate=activateMemberAccount;activateMemberAccount=function(id){oldActivate(id);let m=S.members.find(m=>m.id===id);if(!m.annualDueDate){let d=new Date();d.setFullYear(d.getFullYear()+1);m.annualDueDate=localDay(d)}let g=S.guests.find(g=>g.memberId===id);if(g)g.status='approved';save()};
window.manualGuestForm=()=>{if(!canDept('guests'))return;openModal('Bổ sung người tham dự',`<form onsubmit="saveManualGuest(event)"><div class="form-grid">${select('manualMeeting','Buổi họp',S.meetings.map(m=>[m.id,m.name]),activeMeeting().id)}${select('manualType','Nhóm',[['guest_external','Khách ngoài VBNA'],['guest_vbna','Khách trong VBNA']])}${field('manualName','Họ tên','','text','required')}${field('manualPhone','Số điện thoại','','tel','required')}${field('manualCompany','Doanh nghiệp')}${field('manualChapter','Chapter')}${select('manualInviter','Người mời',[['','Không có'],...actives().map(m=>[m.id,m.fullName])])}${field('manualTime','Thời gian đến',activeMeeting().date+'T13:30','datetime-local','required')}${area('manualReason','Lý do bổ sung')}</div><button class="btn btn-wine">Ghi nhận</button></form>`)};
window.saveManualGuest=e=>{e.preventDefault();if(!canDept('guests'))return;if(!requireName(val('manualName'))||!val('manualReason'))return toast('Nhập tên đúng định dạng và lý do bổ sung');let mid=val('manualMeeting'),phone=val('manualPhone').replace(/\s/g,'');if(S.attendance.some(a=>a.meetingId===mid&&a.phone===phone))return toast('Người này đã có trong điểm danh');let g=S.guests.find(g=>g.phone===phone);if(!g){g={id:uid('G'),fullName:val('manualName'),phone,company:val('manualCompany'),email:'',industry:'',status:'attended',inviterId:val('manualInviter'),createdAt:iso()};S.guests.push(g)}S.attendance.push({id:uid('AT'),meetingId:mid,personType:'guest',personId:g.id,fullName:g.fullName,phone,company:g.company,role:'Khách mời',chapter:val('manualType')==='guest_external'?'Khách':val('manualChapter'),guestCategory:val('manualType'),inviterId:val('manualInviter'),checkedAt:new Date(val('manualTime')+':00+07:00').toISOString(),manual:true,manualReason:val('manualReason'),createdBy:currentUser().id});save();log('Bổ sung điểm danh','Attendance',g.fullName);closeModal();renderDepartmentsV6()};
const oldMemberForm=memberForm;memberForm=function(m){oldMemberForm(m);q('#memberForm .form-grid').insertAdjacentHTML('beforeend',field('mfSecondary','Ngành nghề phụ',m?.secondaryIndustry||'')+field('mfAvatar','Ảnh đại diện','','file','accept="image/png,image/jpeg,image/webp"'));};
const oldSaveMember=window.saveMember;window.saveMember=async(e,id)=>{if(!canLead()){e.preventDefault();return toast('Bạn không có quyền sửa hồ sơ tại đây')}if(!requireName(val('mfName'))){e.preventDefault();return}if(S.members.some(m=>m.id!==id&&m.phone===val('mfPhone'))){e.preventDefault();return toast('Số điện thoại đã được sử dụng')}const secondary=val('mfSecondary');let photo;try{photo=await readImage(q('#mfAvatar'))}catch(err){e.preventDefault();return toast(err.message)}let before=id?structuredClone(S.members.find(m=>m.id===id)):null;await oldSaveMember(e,id);let m=id?S.members.find(m=>m.id===id):S.members.at(-1);m.secondaryIndustry=secondary;if(photo)m.avatar=photo;auditChange('Cập nhật hồ sơ','Member',before,m)};
const oldStatusForm=window.requestMemberStatus;window.requestMemberStatus=(id,status)=>{if(!canLead())return toast('Chỉ người quản lý hội viên được thao tác');oldStatusForm(id,status);q('#msReason').parentElement.insertAdjacentHTML('beforebegin',select('msReasonKind','Nhóm nguyên nhân',['Tự nguyện','Nợ phí quỹ','Vắng quá số buổi','Vi phạm tư cách hội viên','Khác']));};
const oldStatusSubmit=window.submitMemberStatusChange;window.submitMemberStatusChange=async id=>{if(!canLead())return;const r=val('msReason');if(!r)return toast('Nhập lý do cụ thể');q('#msReason').value=val('msReasonKind')+': '+r;await oldStatusSubmit(id)};
const oldOpp=window.submitOpportunity;window.submitOpportunity=e=>{let m=activeMeeting();if(m.status!=='open'){e.preventDefault();return toast('Buổi họp chưa mở hoặc đã đóng nhận cơ hội')}let rows=qa('#opportunityRows tr');if(rows.some(r=>!q('.oppReceiver',r).value||Number(q('.oppValue',r).value)<0||!Number.isFinite(Number(q('.oppValue',r).value)))){e.preventDefault();return toast('Điền người nhận và số tiền hợp lệ cho từng dòng')}const start=S.opportunities.length;oldOpp(e);S.opportunities.slice(start).forEach(o=>{o.giverPhone=S.members.find(m=>m.id===o.giverId)?.phone;S.notifications.push({id:uid('N'),memberId:o.receiverId,opportunityId:o.id,text:`${memberName(o.giverId)} (${o.giverPhone}) vừa trao cho anh/chị một cơ hội.`,createdAt:iso()})});save()};
function renderPortalV6(){renderMemberPortal();let m=currentMember();if(!m)return;const received=S.opportunities.filter(o=>o.receiverId===m.id),given=S.opportunities.filter(o=>o.giverId===m.id);q('#memberPortal').insertAdjacentHTML('afterbegin',`<section class="panel"><div class="toolbar"><h3>Không gian hội viên</h3>${button('Cập nhật hồ sơ','editOwnProfile()','btn-outline')}</div>${S.notifications.filter(n=>n.memberId===m.id).slice(-5).reverse().map(n=>`<p class="notice">${esc(n.text)}</p>`).join('')}<h3>Cơ hội tôi nhận được</h3>${table(['Người trao','Điện thoại','Loại','Dự kiến','Đã xác nhận','Trạng thái','Thao tác'],received.map(o=>[esc(memberName(o.giverId)),esc(o.giverPhone||S.members.find(x=>x.id===o.giverId)?.phone),esc(o.type),money(o.value),o.confirmedAt?money(o.confirmedValue):'—',statusChip(o.status),o.confirmedAt?'Đã xác nhận':button('Xác nhận',`confirmOpportunityForm('${o.id}')`,'btn-outline btn-sm')]))}<h3>Lịch sử trao cơ hội</h3>${table(['Người nhận','Ngày','Dự kiến','Doanh thu đã nhận','Kết quả'],given.map(o=>[esc(o.receiverName),fmtDate(o.createdAt),money(o.value),o.confirmedAt?money(o.confirmedValue):'—',statusChip(o.status)]))}</section><section class="panel"><h3>Các khoản phải nộp của tôi</h3>${table(['Khoản thu','Hạn nộp','Phải thu','Đã thu','Còn nợ'],S.obligations.filter(o=>o.memberId===m.id).map(o=>[esc(o.label),fmtDate(o.due),money(o.amount),money(paidFor(o.id)),money(debtFor(o))]))}</section>`)}
window.confirmOpportunityForm=id=>{const o=S.opportunities.find(o=>o.id===id);if(!o||o.receiverId!==currentMember()?.id||o.confirmedAt)return toast('Không thể xác nhận cơ hội này');openModal('Xác nhận kết quả cơ hội',`<form onsubmit="saveOpportunityResult(event,'${id}')"><p>Người trao: ${esc(memberName(o.giverId))} · ${esc(o.giverPhone||'')}</p><div class="form-grid">${select('orStatus','Kết quả',[['success','Thành công — đã nhận tiền'],['failed','Không thành công']])}${field('orAmount','Số tiền thực nhận (đ)',0,'number','min="0" required')}${area('orReason','Lý do không thành công / Ghi chú')}</div><div class="form-actions"><button class="btn btn-wine">Xác nhận kết quả</button></div></form>`)};
window.saveOpportunityResult=(e,id)=>{e.preventDefault();let o=S.opportunities.find(o=>o.id===id);if(!o||o.receiverId!==currentMember()?.id||o.confirmedAt)return;let status=val('orStatus'),amount=Number(val('orAmount'));if(status==='failed'&&!val('orReason'))return toast('Vui lòng ghi lý do không thành công');if(status==='success'&&(!Number.isFinite(amount)||amount<=0))return toast('Nhập số tiền thực nhận lớn hơn 0');const before=structuredClone(o);o.status=status;o.confirmedValue=status==='success'?amount:0;o.confirmedAt=iso();o.confirmedBy=currentUser().id;o.failureReason=val('orReason');auditChange('Xác nhận cơ hội','Opportunity',before,o);closeModal();renderPortalV6();toast('Đã ghi nhận kết quả cho cả người trao và người nhận','success')};
window.editOwnProfile=()=>{const m=currentMember();if(!m)return;openModal('Cập nhật hồ sơ của tôi',`<form onsubmit="saveOwnProfile(event)"><div class="form-grid">${field('pfName','Họ tên',m.fullName,'text','required')}${field('pfPhone','Số điện thoại',m.phone,'tel','required')}${field('pfEmail','Email',m.email,'email','required')}${field('pfCompany','Doanh nghiệp',m.company)}${field('pfAddress','Địa chỉ doanh nghiệp',m.businessAddress)}${field('pfIndustry','Ngành nghề chính',m.industry)}${field('pfSecondary','Ngành nghề phụ',m.secondaryIndustry)}${field('pfPhoto','Ảnh đại diện','','file','accept="image/png,image/jpeg,image/webp"')}</div><div class="form-actions"><button class="btn btn-wine">Gửi Chủ tịch / Admin duyệt</button></div></form>`)};
window.saveOwnProfile=async e=>{e.preventDefault();let m=currentMember();if(!m||!requireName(val('pfName')))return;if(S.members.some(x=>x.id!==m.id&&x.phone===val('pfPhone')))return toast('Số điện thoại đã tồn tại');try{let p={fullName:val('pfName'),phone:val('pfPhone'),email:val('pfEmail'),company:val('pfCompany'),businessAddress:val('pfAddress'),industry:val('pfIndustry'),secondaryIndustry:val('pfSecondary')},photo=await readImage(q('#pfPhoto'));if(photo)p.avatar=photo;requestApproval('profile',m.id,'Cập nhật hồ sơ '+m.fullName,p);closeModal();toast('Đã gửi hồ sơ chờ phê duyệt','success')}catch(err){toast(err.message)}};
function trainingHTML(){let list=S.training;return stats([['Buổi họp',S.meetings.length],['Bài đào tạo',list.length],['Tệp đã đăng',list.reduce((n,t)=>n+t.files.length,0)]])+`<section class="panel"><div class="toolbar"><h3>Tri thức từ cộng đồng</h3>${button('Đăng bài đào tạo','trainingForm()')}</div><div class="news-grid">${list.map(t=>`<article class="news-card"><span class="eyebrow">${esc(t.field)}</span><h3>${esc(t.title)}</h3><small>${fmtDate(t.date)} · ${esc(t.trainer)}</small><p>${esc(t.description)}</p><small>Đăng bởi ${esc(userName(t.createdBy))}</small><div>${t.files.map(f=>button(esc(f.name),`downloadStoredFile('${f.storageKey}')`,'btn-outline btn-sm')).join('')}</div><div class="reaction-bar">${button('👍 '+Object.values(t.votes).filter(v=>v===1).length,`voteTraining('${t.id}',1)`,'btn-soft btn-sm')}${button('👎 '+Object.values(t.votes).filter(v=>v===-1).length,`voteTraining('${t.id}',-1)`,'btn-soft btn-sm')}${button('Góp ý ('+t.comments.length+')',`trainingComment('${t.id}')`,'btn-outline btn-sm')}</div></article>`).join('')||empty('Chưa có bài đào tạo. Chia sẻ kiến thức đầu tiên với cộng đồng.')}</div></section>`}
window.trainingForm=()=>{if(!currentUser())return;openModal('Đăng bài đào tạo',`<form onsubmit="saveTraining(event)"><div class="form-grid">${field('trTitle','Tên bài','','text','required')}${field('trField','Lĩnh vực','','text','required')}${field('trTrainer','Người đào tạo',currentMember()?.fullName||'','text','required')}${field('trDate','Ngày đào tạo',localDay(),'date','required')}${select('trMeeting','Buổi họp',[['','Không gắn buổi họp'],...S.meetings.map(m=>[m.id,m.name])])}${field('trFiles','Tài liệu','','file','multiple')}${area('trDescription','Nội dung giới thiệu')}</div><div class="form-actions"><button class="btn btn-wine">Đăng bài</button></div></form>`)};
window.saveTraining=async e=>{e.preventDefault();if(!currentUser())return;try{let files=await persistInputFiles(q('#trFiles'),10,'training');S.training.unshift({id:uid('TR'),title:val('trTitle'),field:val('trField'),trainer:val('trTrainer'),date:val('trDate'),meetingId:val('trMeeting'),description:val('trDescription'),files,createdBy:currentUser().id,createdAt:iso(),votes:{},comments:[]});save();log('Đăng bài đào tạo','Training',val('trTitle'));closeModal();renderDepartmentsV6()}catch(e){toast(e.message)}};
window.voteTraining=(id,v)=>{if(!currentUser())return;let t=S.training.find(t=>t.id===id);if(!t)return;if(t.votes[currentUser().id]===v)delete t.votes[currentUser().id];else t.votes[currentUser().id]=v;save();renderDepartmentsV6()};
window.trainingComment=id=>{let t=S.training.find(t=>t.id===id);if(!t)return;openModal('Góp ý: '+t.title,t.comments.map(c=>`<article class="notice"><b>${esc(userName(c.userId))}</b><p>${esc(c.body)}</p></article>`).join('')+`<form onsubmit="saveTrainingComment(event,'${id}')">${area('trComment','Ý kiến của anh/chị')}<button class="btn btn-wine">Gửi góp ý</button></form>`)};
window.saveTrainingComment=(e,id)=>{e.preventDefault();if(!currentUser()||!val('trComment'))return;S.training.find(t=>t.id===id).comments.push({id:uid('C'),userId:currentUser().id,body:val('trComment'),createdAt:iso()});save();trainingComment(id)};
function visiblePost(p){if(p.status!=='approved')return false;if(p.scope==='public')return true;let u=currentUser();if(!u)return false;if(canLead())return true;return p.audience.includes('all')||p.audience.includes(u.role)||p.audience.includes('lt')&&S.departments.some(d=>d.leadRole===u.role)||p.audience.some(id=>currentMember()?.departmentIds.includes(id))}
function postsHTML(scope){let list=S.posts.filter(p=>scope==='public'?p.scope==='public'&&p.status==='approved':p.department===scope&&(visiblePost(p)||canDept(scope)));return `<div class="news-grid">${list.map(p=>`<article class="news-card">${p.important?'<span class="chip red">Quan trọng</span>':''} <span class="chip gray">${p.status==='approved'?'Đã duyệt':'Chờ duyệt'}</span><h3>${esc(p.title)}</h3><small>${fmtDate(p.createdAt)}</small><p>${esc(p.body)}</p>${p.file?.storageKey?button('Tải thông báo',`downloadStoredFile('${p.file.storageKey}')`,'btn-outline btn-sm'):''}${p.sponsorship&&currentMember()&&p.status==='approved'?button('Đăng ký tài trợ',`pledgeForm('${p.id}')`,'btn-outline'):''}</article>`).join('')||empty('Chưa có thông báo.')}</div>`}
window.postForm=dep=>{if(!canDept(dep))return;openModal('Đăng thông báo',`<form onsubmit="savePost(event,'${dep}')"><div class="form-grid">${field('poTitle','Tiêu đề','','text','required')}${select('poScope','Phạm vi',dep==='orientation'?[['internal','Nội bộ']]:[['internal','Nội bộ'],['public','Công khai & nội bộ']])}${area('poBody','Nội dung')}${select('poAudience','Đối tượng',[['all','Toàn bộ hội viên & LT'],['lt','Toàn bộ LT'],...S.departments.map(d=>[d.id,d.name])])}${field('poFile','Văn bản đính kèm','','file')}<label class="inline-check"><input type="checkbox" id="poImportant"> Quan trọng — hiển thị popup</label>${dep==='secretariat'?'<label class="inline-check"><input type="checkbox" id="poSponsor" checked> Cho phép đăng ký tài trợ</label>':''}</div><div class="form-actions"><button class="btn btn-wine">${canLead()?'Đăng thông báo':'Gửi phê duyệt'}</button></div></form>`)};
window.savePost=async(e,dep)=>{e.preventDefault();if(!canDept(dep)||!val('poBody'))return toast('Nhập nội dung thông báo');const files=await persistInputFiles(q('#poFile'),1,'announcement');let p={id:uid('POST'),title:val('poTitle'),body:val('poBody'),department:dep,scope:dep==='orientation'?'internal':val('poScope'),audience:qa('.postAudience:checked').map(x=>x.value),important:!!q('#poImportant').checked,sponsorship:!!q('#poSponsor')?.checked,file:files[0]||null,status:canLead()?'approved':'pending',createdBy:currentUser().id,createdAt:iso()};S.posts.unshift(p);if(!canLead())requestApproval('post',p.id,'Đăng thông báo: '+p.title,{});save();log('Tạo thông báo','Post',p.title);closeModal();if(document.body.dataset.page==='finance')renderFinanceV6();else renderDepartmentsV6()};
function showPostNotifications(){if(document.body.dataset.page==='lucky')return;let identity=currentUser()?.id||'public';let list=S.posts.filter(p=>p.important&&visiblePost(p)&&!sessionStorage.getItem('postSeen:'+identity+':'+p.id));if(list.length){list.forEach(p=>sessionStorage.setItem('postSeen:'+identity+':'+p.id,'1'));setTimeout(()=>{if(q('#modal:not(.hide)'))return;openModal('Thông báo Chapter 11',list.map(p=>`<article class="notice"><h3>${esc(p.title)}</h3><p class="prose">${esc(p.body)}</p>${p.sponsorship&&currentMember()?button('Đăng ký tài trợ',`pledgeForm('${p.id}')`):''}</article>`).join(''))},400)}}
let ytPlayer=null,ytReady=false;
function enhanceLucky(){q('.lucky-brand-row').innerHTML=`<div class="lucky-brand"><img id="vbnaLogoPreview" class="${S.config.site.leftLogo?'':'hide'}" src="${esc(imageSrc(S.config.site.leftLogo))}" alt="Logo trái Chapter 11"></div><div class="lucky-brand"><img id="c11LogoPreview" class="${S.config.site.rightLogo?'':'hide'}" src="${esc(imageSrc(S.config.site.rightLogo))}" alt="Logo phải VBNA"></div>`;q('#musicFile')?.parentElement.querySelector('.notice')?.remove();q('#musicFile')?.insertAdjacentHTML('beforebegin','<div id="youtubePlayer"></div><p class="small-text">Nhạc YouTube đã chọn. Nếu trình duyệt chặn tự phát, bấm Phát nhạc.</p>');let script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';document.head.append(script);window.onYouTubeIframeAPIReady=()=>{ytPlayer=new YT.Player('youtubePlayer',{height:200,width:260,videoId:'XFZLGyt805c',playerVars:{playsinline:1,loop:1,playlist:'XFZLGyt805c',origin:location.origin},events:{onReady:()=>{ytReady=true;ytPlayer.playVideo()},onError:()=>toast('YouTube không phát được. Anh/chị có thể mở liên kết gốc hoặc chọn file nhạc.')}})};q('#bgFile').onchange=async e=>{try{let src=await readImage(e.target);if(src){S.lucky.background=src;save();q('.lucky').style.setProperty('background-image',`url("${src}")`,'important')}}catch(err){toast(err.message)}};if(S.lucky.background)q('.lucky').style.setProperty('background-image',`url("${S.lucky.background}")`,'important');q('#vbnaLogo').onchange=async e=>{let src=await readImage(e.target);if(src){S.config.site.leftLogo=src;save();q('#vbnaLogoPreview').src=src;q('#vbnaLogoPreview').classList.remove('hide')}};q('#c11Logo').onchange=async e=>{let src=await readImage(e.target);if(src){S.config.site.rightLogo=src;save();q('#c11LogoPreview').src=src;q('#c11LogoPreview').classList.remove('hide')}}}
startDefaultLuckyMusic=function(){if(ytReady)ytPlayer.playVideo()};stopDefaultLuckyMusic=function(){if(ytReady)ytPlayer.pauseVideo()};
window.toggleLuckyMusic=()=>{let a=q('#customLotteryAudio');if(a.src){if(a.paused)a.play().catch(()=>toast('Bấm phát trên trình duyệt để cho phép âm thanh'));else a.pause();return}if(!ytReady)return toast('Đang tải YouTube. Hãy kiểm tra kết nối mạng.');ytPlayer.getPlayerState()===1?ytPlayer.pauseVideo():ytPlayer.playVideo()};
