function membersAt(date){return S.members.filter(m=>(!m.admitDate||m.admitDate<=date)&&(!m.stopDate||m.stopDate>date)&&m.status!=='pending')}
function meetingFacts(m){
 const roster=membersAt(m.date),ids=new Set(roster.map(x=>x.id));
 const at=S.attendance.filter(a=>a.meetingId===m.id),present=at.filter(a=>a.personType==='member'&&ids.has(a.personId)),unique=[...new Map(present.map(a=>[a.personId,a])).values()];
 const guests=at.filter(a=>a.personType!=='member'),internal=guests.filter(a=>a.guestCategory!=='guest_external'&&a.chapter&&a.chapter!=='Khách');
 const ops=S.opportunities.filter(o=>o.meetingId===m.id),start=new Date(m.date+'T00:00:00+07:00'),prev=new Date(start.getTime()-7*86400000),prevDay=localDay(prev);
 const confirmed=S.opportunities.filter(o=>o.receiverType==='member'&&o.status==='success'&&o.confirmedAt&&localDay(o.confirmedAt)>=prevDay&&localDay(o.confirmedAt)<m.date&&localDay(o.createdAt)>=prevDay&&localDay(o.createdAt)<m.date);
 const cumulative=S.opportunities.filter(o=>o.receiverType==='member'&&o.status==='success'&&o.confirmedAt&&localDay(o.confirmedAt)>=S.config.openingRevenueDate&&localDay(o.confirmedAt)<=m.date);
 const top=(xs,key)=>{let map={};xs.forEach(x=>{if(x[key])map[x[key]]=(map[x[key]]||0)+1});let e=Object.entries(map).sort((a,b)=>b[1]-a[1]);return e[0]?memberName(e[0][0]):'—'};
 const best=confirmed.slice().sort((a,b)=>b.confirmedValue-a.confirmedValue)[0];
 const earliest=unique.slice().sort((a,b)=>a.checkedAt.localeCompare(b.checkedAt))[0];
 return {roster,at,present:unique,internal,external:guests.filter(a=>!internal.includes(a)),ops,confirmed,newMembers:roster.filter(x=>x.admitDate>=prevDay&&x.admitDate<=m.date).length,openIndustries:S.powerTeams.reduce((n,p)=>n+p.openIndustries.length,0),success:sum(confirmed,'confirmedValue'),cumulative:Number(S.config.openingRevenue||0)+sum(cumulative,'confirmedValue'),topGiver:top(ops,'giverId'),topInviter:top(S.attendance.filter(a=>a.personType!=='member'&&localDay(a.checkedAt)>=prevDay&&localDay(a.checkedAt)<m.date),'inviterId'),best:best?memberName(best.giverId):'—',earliest:earliest?.fullName||'—',ratio:roster.length?unique.length/roster.length:0};
}
function attendanceRows(m){let f=meetingFacts(m);return f.roster.map((mem,i)=>{let a=f.present.find(a=>a.personId===mem.id),note=S.attendanceNotes.find(n=>n.meetingId===m.id&&n.memberId===mem.id)||{},t=a?clockVN(a.checkedAt):'';let late=a&&new Date(a.checkedAt).toLocaleTimeString('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour12:false})>'14:00:00',early=!!note.early;return [i+1,mem.fullName,'13:30',t||'—',[late?'Đi muộn':'',early?'Về sớm':''].filter(Boolean).join(', ')||'—',note.status==='sick'?'Có':'',note.status==='substitute'?note.substitute||'Có':'',!a&&!['sick','substitute'].includes(note.status)?'Vắng mặt':'',note.reason||'']})}
const weeklyHeaders=['TT','Ngày tháng','Tuần','Số HV','HV hiện diện','Khách ngoài VBNA','Khách trong VBNA','Kết nạp HV mới','Ngành nghề đang mở','Cơ hội trao','Giá trị thành công tuần trước','Giá trị cộng dồn','HV trao cơ hội chất lượng nhất','HV trao nhiều cơ hội nhất','HV có nhiều khách mời tuần trước','HV hiện diện sớm nhất','Ghi chú','Tỷ lệ hiện diện'];
function weeklyRows(meetings){return meetings.map((m,i)=>{let f=meetingFacts(m);return [i+1,m.date,m.termWeek,f.roster.length,f.present.length,f.external.length,f.internal.length,f.newMembers,f.openIndustries,f.ops.length,f.success,f.cumulative,f.best,f.topGiver,f.topInviter,f.earliest,m.reportNote||'',Math.round(f.ratio*10000)/100+'%']})}
function selectedDates(){if(!q('#reportFrom'))return {from:'1900-01-01',to:'9999-12-31'};return {from:val('reportFrom')||S.config.term.start,to:val('reportTo')||S.config.term.end}}
function periodControls(){let y=new Date().getFullYear();return `<div class="filters no-print">${select('reportPeriod','Kỳ báo cáo',[['term','Nhiệm kỳ'],['week','Tuần hiện tại'],['month','Tháng hiện tại'],['quarter','Quý hiện tại'],['year','Năm hiện tại'],['custom','Tùy chọn']])}${field('reportFrom','Từ ngày',S.config.term.start,'date')}${field('reportTo','Đến ngày',S.config.term.end,'date')}${button('Áp dụng','refreshReportView()','btn-outline')}</div>`}
window.changePeriod=()=>{let d=new Date(),y=d.getFullYear(),month=d.getMonth(),p=val('reportPeriod'),from=S.config.term.start,to=S.config.term.end;let date=(m,day)=>localDay(new Date(y,m,day,12));if(p==='year'){from=`${y}-01-01`;to=`${y}-12-31`}if(p==='month'){from=date(month,1);to=date(month+1,0)}if(p==='quarter'){let start=Math.floor(month/3)*3;from=date(start,1);to=date(start+3,0)}if(p==='week'){let start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));from=localDay(start);start.setDate(start.getDate()+6);to=localDay(start)}if(p!=='custom'){q('#reportFrom').value=from;q('#reportTo').value=to}};
function reportDatasets(mode='all'){
 const {from,to}=selectedDates();if(from>to)throw Error('Ngày bắt đầu phải trước ngày kết thúc');const within=d=>d&&localDay(d)>=from&&localDay(d)<=to;
 const meetings=S.meetings.filter(m=>m.date>=from&&m.date<=to).sort((a,b)=>a.date.localeCompare(b.date));
 const result=[];if(['all','vice','president'].includes(mode)){
 result.push({name:'Tong hop tuan',headers:weeklyHeaders,rows:weeklyRows(meetings)});
 const m=S.meetings.find(m=>m.id===val('reportMeeting'))||activeMeeting(),f=meetingFacts(m);
 result.push({name:'Diem danh buoi hop',headers:['STT','Hội viên','Giờ bắt đầu','Giờ đến','Đi muộn / Về sớm','Nghỉ ốm','Đi thay','Vắng mặt','Ghi chú'],rows:attendanceRows(m)});
 result.push({name:'Tong ket buoi hop',headers:['Nội dung','Kết quả'],rows:[['Buổi họp',m.name],['Ngày',m.date],['Tổng hội viên',f.roster.length],['Hội viên hiện diện',f.present.length],['Kết nạp mới',f.newMembers],['Ngành nghề đang mở',f.openIndustries],['Khách trong VBNA',f.internal.length],['Khách ngoài VBNA',f.external.length],['Cơ hội buổi họp',f.ops.length],['Doanh thu xác nhận của cơ hội tuần trước',f.success],['Doanh số cộng dồn',f.cumulative],['Trao nhiều cơ hội nhất',f.topGiver],['Mời nhiều khách nhất tuần trước',f.topInviter]]});
 }
 if(['all','president','guests'].includes(mode)){let at=S.attendance.filter(a=>within(a.checkedAt));result.push({name:'Khach moi',headers:['Họ tên','SĐT','Doanh nghiệp','Phân loại','Chapter','Người mời','Buổi họp','Check-in'],rows:at.filter(a=>a.personType!=='member').map(a=>[a.fullName,a.phone,a.company,a.guestCategory||a.role,a.chapter,memberName(a.inviterId),S.meetings.find(m=>m.id===a.meetingId)?.name,a.checkedAt])});result.push({name:'CRM',headers:['Họ tên','SĐT','Email','Ngành nghề','Người mời','Trạng thái'],rows:S.guests.filter(g=>within(g.createdAt)).map(g=>[g.fullName,g.phone,g.email,g.industry,memberName(g.inviterId),g.status])})}
 if(['all','president','training'].includes(mode))result.push({name:'Dao tao',headers:['Bài đào tạo','Lĩnh vực','Người đào tạo','Ngày','Người đăng','Tệp','Thích','Không thích','Ý kiến'],rows:S.training.filter(t=>within(t.date)).map(t=>[t.title,t.field,t.trainer,t.date,userName(t.createdBy),t.files.length,Object.values(t.votes).filter(x=>x===1).length,Object.values(t.votes).filter(x=>x===-1).length,t.comments.length])});
 if(['all','president','events','orientation'].includes(mode))result.push({name:'Truyen thong',headers:['Tiêu đề','Ban','Ngày','Phạm vi','Đối tượng','Trạng thái'],rows:S.posts.filter(p=>within(p.createdAt)&&(mode==='all'||mode==='president'||p.department===mode)).map(p=>[p.title,p.department,p.createdAt,p.scope,p.audience.join(', '),p.status])});
 if(['all','president','development'].includes(mode))result.push({name:'Power Team',headers:['Power Team','Số hội viên','Ngành nghề mở'],rows:S.powerTeams.map(p=>[p.name,actives().filter(m=>m.powerTeamId===p.id).length,p.openIndustries.join(', ')])});
 if(['all','president'].includes(mode)){result.push({name:'Co hoi',headers:['Ngày','Người trao','SĐT người trao','Người nhận','Loại','Giá trị dự kiến','Trạng thái','Doanh thu xác nhận','Ngày xác nhận','Lý do không thành công'],rows:S.opportunities.filter(o=>within(o.createdAt)).map(o=>[o.createdAt,memberName(o.giverId),S.members.find(m=>m.id===o.giverId)?.phone,o.receiverName,o.type,o.value,o.status,o.confirmedAt?o.confirmedValue:0,o.confirmedAt||'',o.failureReason||''])});
 result.push({name:'Danh gia hoi vien',headers:['Hội viên','Vai trò / Ban','Số buổi trong kỳ','Hiện diện','Tỷ lệ (%)','Trao cơ hội','Nhận cơ hội','Doanh thu mang lại','Khách mời','Bài đào tạo','Đánh giá theo ngưỡng'],rows:S.members.map(m=>{let eligible=meetings.filter(mt=>membersAt(mt.date).some(x=>x.id===m.id)),ids=new Set(eligible.map(x=>x.id)),att=new Set(S.attendance.filter(a=>a.personId===m.id&&ids.has(a.meetingId)).map(a=>a.meetingId)).size,given=S.opportunities.filter(o=>o.giverId===m.id&&within(o.createdAt)),ratio=eligible.length?att/eligible.length*100:null;return [m.fullName,m.departmentIds.map(id=>S.departments.find(d=>d.id===id)?.name).join(', '),eligible.length,att,ratio===null?'Chưa có buổi họp':Math.round(ratio),given.length,S.opportunities.filter(o=>o.receiverId===m.id&&within(o.createdAt)).length,sum(given.filter(o=>o.status==='success'&&o.confirmedAt),'confirmedValue'),S.attendance.filter(a=>a.inviterId===m.id&&within(a.checkedAt)).length,S.training.filter(t=>t.createdBy===S.users.find(u=>u.memberId===m.id)?.id&&within(t.date)).length,ratio===null?'Chưa đủ dữ liệu':ratio>=S.config.assessment.attendance&&given.length>=S.config.assessment.referrals?'Đạt ngưỡng tham gia':'Cần trao đổi thêm']})});}
 if(['all','president','secretariat'].includes(mode)&&financeAccess()){
 const fs=S.finance.filter(f=>within(f.date));result.push({name:'So quy',headers:['Mã phiếu','Ngày','Thu / Chi','Danh mục','Diễn giải','Số tiền','Phương thức','Trạng thái','Người nhập','Ngày tạo'],rows:fs.map(f=>[f.id,f.date,f.kind==='income'?'Thu':'Chi',f.category,f.description,f.amount,f.method||'',f.status,userName(f.createdBy),f.createdAt||''])});
 result.push({name:'Cong no',headers:['Hội viên','Email','SĐT','Khoản thu','Hạn nộp','Phải thu','Đã thu','Còn nợ','Số ngày quá hạn'],rows:S.obligations.map(o=>{let m=S.members.find(m=>m.id===o.memberId);return [m?.fullName,m?.email,m?.phone,o.label,o.due,o.amount,paidFor(o.id),debtFor(o),overdueDays(o)]})});
 result.push({name:'Tai tro',headers:['Hội viên','Nội dung','Cam kết','Đã nhận','Ngày'],rows:S.pledges.map(p=>[memberName(p.memberId),S.posts.find(x=>x.id===p.postId)?.title,p.amount,p.received||0,p.createdAt])});}
 return result;
}
function allowedReportMode(){const u=currentUser();if(canLead())return val('reportMode')||'all';let d=S.departments.find(d=>d.leadRole===u?.role);return d?.id||'member'}
function reportAllowed(mode){return canLead()||(mode!=='all'&&mode!=='president'&&canDept(mode))}
function renderReportPage(){if(!requireAuth())return;let mode=allowedReportMode();if(mode==='member'){document.body.innerHTML=publicHeader()+`<main class="container section">${empty('Báo cáo chi tiết dành cho Trưởng ban, Chủ tịch và Admin.')}<a class="btn btn-outline" href="departments.html">Về Dashboard các Ban</a></main>`;return}
 document.body.innerHTML=`<main class="report-page"><div class="page-tools"><div><span class="eyebrow">VBNA CHAPTER 11</span><h1>Báo cáo hoạt động</h1></div><a class="btn btn-outline" href="departments.html">Dashboard các Ban</a></div><section class="panel">${periodControls()}<div class="filters">${canLead()?select('reportMode','Phân hệ',[['all','Toàn bộ'],...S.departments.filter(d=>d.id!=='support_director').map(d=>[d.id,d.name])]):''}${select('reportMeeting','Buổi họp chi tiết',S.meetings.map(m=>[m.id,m.name]),activeMeeting().id)}${button('Xuất Excel (.xlsx)','exportV6Report()')}${button('In / Lưu PDF','window.print()','btn-outline')}</div><p class="small-text">Doanh thu chỉ tính cơ hội được hội viên nhận xác nhận. Đánh giá tham gia: hiện diện ≥ ${S.config.assessment.attendance}% và trao ≥ ${S.config.assessment.referrals} cơ hội trong kỳ.</p></section><div id="reportOutput"></div></main>`;q('#reportPeriod').onchange=changePeriod;q('#reportMode')?.addEventListener('change',refreshReportView);q('#reportMeeting').onchange=refreshReportView;refreshReportView();}
window.refreshReportView=()=>{try{let mode=allowedReportMode();if(!reportAllowed(mode))return;let data=reportDatasets(mode);q('#reportOutput').innerHTML=data.map(d=>`<section class="panel report-block"><h2 class="report-title">${esc(d.name)}</h2>${table(d.headers,d.rows.map(r=>r.map(v=>esc(v))))}</section>`).join('')}catch(e){toast(e.message)}};
window.exportV6Report=async(mode)=>{mode=mode||allowedReportMode();if(!reportAllowed(mode))return toast('Bạn không có quyền xuất báo cáo này');try{await exportXlsx(reportDatasets(mode),'VBNA_Chapter11_'+mode+'_'+localDay()+'.xlsx');log('Xuất Excel','Report',mode)}catch(e){toast(e.message)}};
window.exportReportCsv=()=>exportV6Report(canLead()?'all':allowedReportMode());
async function exportXlsx(sheets,name){
 const zip=new JSZip(),xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');
 const col=n=>{let x='';for(n++;n>0;n=Math.floor((n-1)/26))x=String.fromCharCode(65+(n-1)%26)+x;return x};
 zip.file('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
 zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 zip.file('xl/workbook.xml',`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
 zip.file('xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rStyle" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
 zip.file('xl/styles.xml','<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFED233C"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
 sheets.forEach((s,i)=>{let rows=[s.headers,...s.rows];zip.file(`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${s.headers.map((h,c)=>`<col min="${c+1}" max="${c+1}" width="${c===0?20:28}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((r,ri)=>`<row r="${ri+1}" ht="${ri?36:42}" customHeight="1">${r.map((v,c)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${col(c)}${ri+1}" s="0"><v>${v}</v></c>`:`<c r="${col(c)}${ri+1}" t="inlineStr" s="${ri?0:1}"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col(s.headers.length-1)}${rows.length}"/></worksheet>`)});
 downloadBlob(await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',compression:'DEFLATE'}),name);
}
